### ISSUE TITLE
Unable to build with older version of `bindgen`

### ISSUE THREAD

**Issue by rongcuid** [twistedfall/opencv-rust#142]
I am on Pop OS (Ubuntu) 20.04, with system opencv and default llvm/clang installed.
Trying to build without `buildtime-bindgen` fails with linking error, while with bindgen I get some problem on bindgen itself.

OpenCV is 4.2.0

Short version:

``` shell script
$ cargo build
   Compiling opencv v0.41.0
error: failed to run custom build command for `opencv v0.41.0`

Caused by:
  process didn't exit successfully: `/home/rongcuid/Projects/CVLive/target/debug/build/opencv-8ea17675d8494eee/build-script-build` (exit code: 101)
--- stderr
=== Crate version: Some("0.41.0")
=== Environment configuration:
===   OPENCV_HEADER_DIR = None
===   OPENCV_PACKAGE_NAME = None
===   OPENCV_PKGCONFIG_NAME = None
===   OPENCV_CMAKE_NAME = None
===   OPENCV_CMAKE_BIN = None
===   OPENCV_VCPKG_NAME = None
===   OPENCV_LINK_LIBS = None
===   OPENCV_LINK_PATHS = None
===   OPENCV_INCLUDE_PATHS = None
===   OPENCV_DISABLE_PROBES = None
===   OPENCV_CLANG_STDLIB_PATH = None
===   CMAKE_PREFIX_PATH = None
===   OpenCV_DIR = None
===   PKG_CONFIG_PATH = None
===   VCPKG_ROOT = None
=== Enabled features:
===   BINDING_GENERATOR
===   BUILDTIME_BINDGEN
===   CLANG
===   DEFAULT
===   JOBSERVER
===   OPENCV_4
=== Probing OpenCV library using pkg_config
=== OpenCV library configuration: Library {
    include_paths: [
        "/usr/include/opencv4/opencv",
        "/usr/include/opencv4",
    ],
    version: "4.2.0",
    cargo_metadata: [
        "cargo:rustc-link-search=native=/usr/lib/x86_64-linux-gnu",
        "cargo:rustc-link-lib=opencv_stitching",
        "cargo:rustc-link-lib=opencv_aruco",
        "cargo:rustc-link-lib=opencv_bgsegm",
        "cargo:rustc-link-lib=opencv_bioinspired",
        "cargo:rustc-link-lib=opencv_ccalib",
        "cargo:rustc-link-lib=opencv_dnn_objdetect",
        "cargo:rustc-link-lib=opencv_dnn_superres",
        "cargo:rustc-link-lib=opencv_dpm",
        "cargo:rustc-link-lib=opencv_highgui",
        "cargo:rustc-link-lib=opencv_face",
        "cargo:rustc-link-lib=opencv_freetype",
        "cargo:rustc-link-lib=opencv_fuzzy",
        "cargo:rustc-link-lib=opencv_hdf",
        "cargo:rustc-link-lib=opencv_hfs",
        "cargo:rustc-link-lib=opencv_img_hash",
        "cargo:rustc-link-lib=opencv_line_descriptor",
        "cargo:rustc-link-lib=opencv_quality",
        "cargo:rustc-link-lib=opencv_reg",
        "cargo:rustc-link-lib=opencv_rgbd",
        "cargo:rustc-link-lib=opencv_saliency",
        "cargo:rustc-link-lib=opencv_shape",
        "cargo:rustc-link-lib=opencv_stereo",
        "cargo:rustc-link-lib=opencv_structured_light",
        "cargo:rustc-link-lib=opencv_phase_unwrapping",
        "cargo:rustc-link-lib=opencv_superres",
        "cargo:rustc-link-lib=opencv_optflow",
        "cargo:rustc-link-lib=opencv_surface_matching",
        "cargo:rustc-link-lib=opencv_tracking",
        "cargo:rustc-link-lib=opencv_datasets",
        "cargo:rustc-link-lib=opencv_text",
        "cargo:rustc-link-lib=opencv_dnn",
        "cargo:rustc-link-lib=opencv_plot",
        "cargo:rustc-link-lib=opencv_ml",
        "cargo:rustc-link-lib=opencv_videostab",
        "cargo:rustc-link-lib=opencv_videoio",
        "cargo:rustc-link-lib=opencv_viz",
        "cargo:rustc-link-lib=opencv_ximgproc",
        "cargo:rustc-link-lib=opencv_video",
        "cargo:rustc-link-lib=opencv_xobjdetect",
        "cargo:rustc-link-lib=opencv_objdetect",
        "cargo:rustc-link-lib=opencv_calib3d",
        "cargo:rustc-link-lib=opencv_imgcodecs",
        "cargo:rustc-link-lib=opencv_features2d",
        "cargo:rustc-link-lib=opencv_flann",
        "cargo:rustc-link-lib=opencv_xphoto",
        "cargo:rustc-link-lib=opencv_photo",
        "cargo:rustc-link-lib=opencv_imgproc",
        "cargo:rustc-link-lib=opencv_core",
    ],
}
=== Found OpenCV library version: 4.2.0 in headers located at: /usr/include/opencv4
=== Using OpenCV headers from: /usr/include/opencv4/opencv2
=== Generating code in: /home/rongcuid/Projects/CVLive/target/debug/build/opencv-d6f399e5d38808f5/out
=== Placing generated bindings into: /home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.41.0/bindings/rust/opencv_4
=== Clang command line args: [
    "-isystem/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9",
    "-isystem/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/x86_64-linux-gnu/c++/9",
    "-isystem/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/backward",
    "-isystem/usr/local/include",
    "-isystem/usr/lib/llvm-10/lib/clang/10.0.0/include",
    "-isystem/usr/include/x86_64-linux-gnu",
    "-isystem/usr/include",
    "-I/usr/include/opencv4",
    "-I/home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.41.0/src_cpp",
    "-DOCVRS_PARSING_HEADERS",
    "-includeocvrs_resolve_types.hpp",
]
thread '<unnamed>' panicked at 'a `libclang` shared library is not loaded on this thread', /home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs:1618:1
thread 'note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
<unnamed>' panicked at 'a `libclang` shared library is not loaded on this thread', /home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs:1618:1
thread '<unnamed>' panicked at 'a `libclang` shared library is not loaded on this thread', /home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs:1618:1
thread '<unnamed>thread '' panicked at 'a `libclang` shared library is not loaded on this thread<unnamed>', ' panicked at 'a `libclang` shared library is not loaded on this thread/home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs', /home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs::1618:1618:11

thread 'thread '<unnamed><unnamed>' panicked at '' panicked at 'a `libclang` shared library is not loaded on this threada `libclang` shared library is not loaded on this thread', ', /home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs:/home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs1618::11618
:1
thread '<unnamed>' panicked at 'a `libclang` shared library is not loaded on this thread', /home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs:1618:1
thread '<unnamed>' panicked at 'a `libclang` shared library is not loaded on this thread', /home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs:1618:1
thread '<unnamed>' panicked at 'a `libclang` shared library is not loaded on this thread', /home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs:1618:1
thread '<unnamed>' panicked at 'a `libclang` shared library is not loaded on this thread', /home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs:1618:1
thread '<unnamed>' panicked at 'a `libclang` shared library is not loaded on this thread', /home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs:1618:1
thread '<unnamed>' panicked at 'a `libclang` shared library is not loaded on this thread', /home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs:1618:1
thread '<unnamed>' panicked at 'a `libclang` shared library is not loaded on this thread', /home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs:1618:1
thread '<unnamed>' panicked at 'a `libclang` shared library is not loaded on this thread', /home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs:1618:1
thread '<unnamed>' panicked at 'a `libclang` shared library is not loaded on this thread', /home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs:1618:1
thread '<unnamed>' panicked at 'a `libclang` shared library is not loaded on this thread', /home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs:1618:1
thread '<unnamed>' panicked at 'a `libclang` shared library is not loaded on this thread', /home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs:1618:1
thread '<unnamed>' panicked at 'a `libclang` shared library is not loaded on this thread', /home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs:1618:1
thread '<unnamed>' panicked at 'a `libclang` shared library is not loaded on this thread', /home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs:1618:1
thread 'thread '<unnamed><unnamed>' panicked at '' panicked at 'a `libclang` shared library is not loaded on this thread', a `libclang` shared library is not loaded on this thread/home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs:', 1618/home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs:1:
1618:1
thread '<unnamed>' panicked at 'a `libclang` shared library is not loaded on this thread', /home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs:1618:1
thread '<unnamed>' panicked at 'a `libclang` shared library is not loaded on this thread', thread '/home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs:<unnamed>1618' panicked at ':a `libclang` shared library is not loaded on this thread1
', /home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs:1618:1
thread '<unnamed>' panicked at 'a `libclang` shared library is not loaded on this thread', /home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs:1618:1
thread 'thread '<unnamed><unnamed>' panicked at '' panicked at 'a `libclang` shared library is not loaded on this threada `libclang` shared library is not loaded on this thread', ', /home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs/home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs::16181618::11

thread '<unnamed>' panicked at 'a `libclang` shared library is not loaded on this thread', /home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs:1618:1
thread '<unnamed>' panicked at 'a `libclang` shared library is not loaded on this thread', /home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs:1618:1
thread 'thread '<unnamed>' panicked at 'a `libclang` shared library is not loaded on this thread', /home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs:1618:1
<unnamed>' panicked at 'a `libclang` shared library is not loaded on this thread', /home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs:1618:1
thread '<unnamed>' panicked at 'a `libclang` shared library is not loaded on this thread', /home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs:1618:1
thread '<unnamed>' panicked at 'a `libclang` shared library is not loaded on this thread', /home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs:1618:1
thread '<unnamed>' panicked at 'a `libclang` shared library is not loaded on this thread', /home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs:1618:1
thread '<unnamed>' panicked at 'a `libclang` shared library is not loaded on this thread', /home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs:1618:1
thread '<unnamed>' panicked at 'a `libclang` shared library is not loaded on this threadthread '', <unnamed>/home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs' panicked at ':a `libclang` shared library is not loaded on this thread1618', :/home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs1:
1618:1
thread 'thread '<unnamed><unnamed>' panicked at 'a `libclang` shared library is not loaded on this thread' panicked at '', a `libclang` shared library is not loaded on this thread/home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs', :/home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs1618::11618
:1
thread 'thread '<unnamed>' panicked at '<unnamed>a `libclang` shared library is not loaded on this thread' panicked at '', a `libclang` shared library is not loaded on this thread/home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs', :/home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs1618::11618
:1
thread 'main' panicked at 'Can't join thread: Any', /home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.41.0/build.rs:172:13
thread '<unnamed>' panicked at 'a `libclang` shared library is not loaded on this thread', /home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs:1618:1
thread '<unnamed>' panicked at 'a `libclang` shared library is not loaded on this thread', /home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.28.1/src/lib.rs:1618:1
```

Full version is too long for comment. I can post it if needed.

**Comment by rongcuid** [comment]
It is due to dependency of my other deps (`gdnative`) which pulls in `bindgen-0.51`. I am posting an issue on their side now.

**Comment by twistedfall** [comment]
Please enable the `clang-runtime` feature to work this around

**Comment by rongcuid** [comment]
> Please enable the `clang-runtime` feature to work this around

Unfortunately, doing so results in a different error:

```bash-shell
   Compiling opencv v0.41.0
error: failed to run custom build command for `opencv v0.41.0`

Caused by:
  process didn't exit successfully: `/home/rongcuid/Projects/CVLive/target/debug/build/opencv-ccd07e4bfe8301e5/build-script-build` (exit code: 1)
--- stdout
running: "/home/rongcuid/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo" "build" "--release" "--package" "opencv-binding-generator" "--bin" "binding-generator"

--- stderr
=== Crate version: Some("0.41.0")
=== Environment configuration:
===   OPENCV_HEADER_DIR = None
===   OPENCV_PACKAGE_NAME = None
===   OPENCV_PKGCONFIG_NAME = None
===   OPENCV_CMAKE_NAME = None
===   OPENCV_CMAKE_BIN = None
===   OPENCV_VCPKG_NAME = None
===   OPENCV_LINK_LIBS = None
===   OPENCV_LINK_PATHS = None
===   OPENCV_INCLUDE_PATHS = None
===   OPENCV_DISABLE_PROBES = None
===   OPENCV_CLANG_STDLIB_PATH = None
===   CMAKE_PREFIX_PATH = None
===   OpenCV_DIR = None
===   PKG_CONFIG_PATH = None
===   VCPKG_ROOT = None
=== Enabled features:
===   BINDING_GENERATOR
===   BUILDTIME_BINDGEN
===   CLANG
===   CLANG_RUNTIME
===   DEFAULT
===   JOBSERVER
===   OPENCV_4
=== Probing OpenCV library using pkg_config
=== OpenCV library configuration: Library {
    include_paths: [
        "/usr/include/opencv4/opencv",
        "/usr/include/opencv4",
    ],
    version: "4.2.0",
    cargo_metadata: [
        "cargo:rustc-link-search=native=/usr/lib/x86_64-linux-gnu",
        "cargo:rustc-link-lib=opencv_stitching",
        "cargo:rustc-link-lib=opencv_aruco",
        "cargo:rustc-link-lib=opencv_bgsegm",
        "cargo:rustc-link-lib=opencv_bioinspired",
        "cargo:rustc-link-lib=opencv_ccalib",
        "cargo:rustc-link-lib=opencv_dnn_objdetect",
        "cargo:rustc-link-lib=opencv_dnn_superres",
        "cargo:rustc-link-lib=opencv_dpm",
        "cargo:rustc-link-lib=opencv_highgui",
        "cargo:rustc-link-lib=opencv_face",
        "cargo:rustc-link-lib=opencv_freetype",
        "cargo:rustc-link-lib=opencv_fuzzy",
        "cargo:rustc-link-lib=opencv_hdf",
        "cargo:rustc-link-lib=opencv_hfs",
        "cargo:rustc-link-lib=opencv_img_hash",
        "cargo:rustc-link-lib=opencv_line_descriptor",
        "cargo:rustc-link-lib=opencv_quality",
        "cargo:rustc-link-lib=opencv_reg",
        "cargo:rustc-link-lib=opencv_rgbd",
        "cargo:rustc-link-lib=opencv_saliency",
        "cargo:rustc-link-lib=opencv_shape",
        "cargo:rustc-link-lib=opencv_stereo",
        "cargo:rustc-link-lib=opencv_structured_light",
        "cargo:rustc-link-lib=opencv_phase_unwrapping",
        "cargo:rustc-link-lib=opencv_superres",
        "cargo:rustc-link-lib=opencv_optflow",
        "cargo:rustc-link-lib=opencv_surface_matching",
        "cargo:rustc-link-lib=opencv_tracking",
        "cargo:rustc-link-lib=opencv_datasets",
        "cargo:rustc-link-lib=opencv_text",
        "cargo:rustc-link-lib=opencv_dnn",
        "cargo:rustc-link-lib=opencv_plot",
        "cargo:rustc-link-lib=opencv_ml",
        "cargo:rustc-link-lib=opencv_videostab",
        "cargo:rustc-link-lib=opencv_videoio",
        "cargo:rustc-link-lib=opencv_viz",
        "cargo:rustc-link-lib=opencv_ximgproc",
        "cargo:rustc-link-lib=opencv_video",
        "cargo:rustc-link-lib=opencv_xobjdetect",
        "cargo:rustc-link-lib=opencv_objdetect",
        "cargo:rustc-link-lib=opencv_calib3d",
        "cargo:rustc-link-lib=opencv_imgcodecs",
        "cargo:rustc-link-lib=opencv_features2d",
        "cargo:rustc-link-lib=opencv_flann",
        "cargo:rustc-link-lib=opencv_xphoto",
        "cargo:rustc-link-lib=opencv_photo",
        "cargo:rustc-link-lib=opencv_imgproc",
        "cargo:rustc-link-lib=opencv_core",
    ],
}
=== Found OpenCV library version: 4.2.0 in headers located at: /usr/include/opencv4
=== Using OpenCV headers from: /usr/include/opencv4/opencv2
=== Generating code in: /home/rongcuid/Projects/CVLive/target/debug/build/opencv-07137c2b26fb7f9f/out
=== Placing generated bindings into: /home/rongcuid/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.41.0/bindings/rust/opencv_4
error: package ID specification `opencv-binding-generator` matched no packages
Error: "Failed to build the bindings generator"

warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by twistedfall** [comment]
Hm, that’s weird, I’ll investigate, thanks for the report!

**Comment by rongcuid** [comment]
FYI, the godot developers bumped the bindgen version on master, but here comes a dependency issue:

```
    Updating crates.io index
    Updating git repository `https://github.com/godot-rust/godot-rust.git`
error: failed to select a version for `clang-sys`.
    ... required by package `bindgen v0.54.0`
    ... which is depended on by `gdnative-sys v0.8.1 (https://github.com/godot-rust/godot-rust.git#4f6fd5e1)`
    ... which is depended on by `gdnative-bindings v0.8.1 (https://github.com/godot-rust/godot-rust.git#4f6fd5e1)`
    ... which is depended on by `gdnative v0.8.1 (https://github.com/godot-rust/godot-rust.git#4f6fd5e1)`
    ... which is depended on by `cvlive-gdnlib v0.1.0 (/home/rongcuid/Projects/CVLive/cvlive-gdnlib)`
versions that meet the requirements `^0.29` are: 0.29.3, 0.29.2, 0.29.1, 0.29.0

the package `clang-sys` links to the native library `clang`, but it conflicts with a previous package which links to `clang` as well:
package `clang-sys v0.28.0`
    ... which is depended on by `clang v0.23.0`
    ... which is depended on by `opencv v0.41.0`
    ... which is depended on by `cvlive v0.1.0 (/home/rongcuid/Projects/CVLive/cvlive-rs)`
    ... which is depended on by `cvlive-viewer v0.1.0 (/home/rongcuid/Projects/CVLive/cvlive-viewer)`

failed to select a version for `clang-sys` which could resolve this conflict
```
It might be a good idea to relax version constraints if possible.

**Comment by rongcuid** [comment]
I notice the "error: package ID specification `opencv-binding-generator` matched no packages" issue occurs only when I try to use a version from `crates.io`. If I clone the repo locally and checkout the release tag, this error does not show.

**Comment by twistedfall** [comment]
> It might be a good idea to relax version constraints if possible.

This is unfortunate, but I don’t have too much options in this case. This is caused by the transitive dependency. The crate depends on the latest `clang`, which depends on `clang-sys` 0.28, but some other your dependency requires 0.29

**Comment by rongcuid** [comment]
Currently I work around version issue by using a local copy and `[patch]` directive. However, I think the package error might be a separate issue.

**Comment by rongcuid** [comment]
The original issue has been worked around by keeping a local version and manually solving version conflicts. I opened a new issue for the new error: #145
