### ISSUE TITLE
Using OpenCV bundled with OpenVino SDK.

### ISSUE THREAD

**Issue by bus710** [twistedfall/opencv-rust#181]
Before reporting an issue please first check the
[troubleshooting guide](https://github.com/twistedfall/opencv-rust/blob/master/README.md#troubleshooting). If
the issue you're encountering is not solved thereby please state the following in your bugreport:

## 0. Background

Hi, I am trying to use this nice package with a pre-built OpenCV, which is bundled with Intel's OpenVino. The SDK works fine with its Cpp/Python demos so that I wanted to try Rust + opencv-rust + OpenVino. I tried to make it work with some variables but I couldn't get a successful result yet so that I would like to share what's going on.

## 1. Operating system

```sh
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
```
## 2. The way you installed OpenCV: package, official binary distribution, manual compilation, etc.

I used OpenVino bundled OpcnCV. It is located under **/opt/intel/openvino_2021/opencv** and has some files as attached:
```sh
$ pwd
/opt/intel/openvino_2021/opencv

$ tree -L 2
.
├── bin
│   └── opencv_version
├── build_params.txt
├── cmake
│   ├── OpenCVConfig.cmake
│   ├── OpenCVConfig-version.cmake
│   ├── OpenCVModules.cmake
│   └── OpenCVModules-release.cmake
├── etc
│   └── licenses
├── include
│   └── opencv2
├── lib
│   ├── libopencv_calib3d.so -> libopencv_calib3d.so.4.5
│   ├── ...
│   └── libopencv_video.so.4.5.0
├── setupvars.sh
├── third-party-programs.txt
└── version.txt

7 directories, 57 files
```

For the variables:
```sh
$ echo $PKG_CONFIG_PATH 
/opt/intel/openvino_2021/data_processing/dl_streamer/lib/pkgconfig:/opt/intel/openvino_2021/data_processing/gstreamer/lib/pkgconfig:

$  echo $OpenCV_DIR 
/opt/intel/openvino_2021/opencv/cmake

$ echo $LD_LIBRARY_PATH
/opt/intel/openvino_2021/data_processing/dl_streamer/lib:/opt/intel/openvino_2021/data_processing/gstreamer/lib:/opt/intel/openvino_2021/opencv/lib:/opt/intel/openvino_2021/deployment_tools/ngraph/lib:/opt/intel/openvino_2021/deployment_tools/inference_engine/external/hddl_unite/lib:/opt/intel/openvino_2021/deployment_tools/inference_engine/external/hddl/lib:/opt/intel/openvino_2021/deployment_tools/inference_engine/external/gna/lib:/opt/intel/openvino_2021/deployment_tools/inference_engine/external/mkltiny_lnx/lib:/opt/intel/openvino_2021/deployment_tools/inference_engine/external/tbb/lib:/opt/intel/openvino_2021/deployment_tools/inference_engine/lib/intel64
```

## 3. OpenCV version

It seems like 0.45.0 or 0.45.1. 

```sh
$ cat /opt/intel/openvino_2021/opencv/version.txt
4.5.0-65-g464efeb7b (OpenVINO/2021.1)
65
releases/openvino/2021.1
464efeb7b07211706d0f2615e16c8d144447d362

General configuration for OpenCV 4.5.0-openvino =====================================
  Version control:               464efeb7b07211706d0f2615e16c8d144447d362

  Platform:
    Timestamp:                   2020-09-29T02:20:56Z
    Host:                        Linux 4.15.0-29-generic x86_64
    CMake:                       3.14.5
    CMake generator:             Ninja
    CMake build tool:            /opt/miniconda/envs/build/bin/ninja
    Configuration:               Release
```

## 4. rustc version (`rustc --version`)

```sh
rustc 1.47.0 (18bf6b4f0 2020-10-07)
```

## 5. Attach the full output of the following command from your project directory:

```shell script
$ RUST_BACKTRACE=full cargo build -vv 

...

     Running `/home/bus710/repo/tmp/projects/rust_opencv/target/debug/build/opencv-16807245944feb34/build-script-build`
[opencv 0.43.3] === Crate version: Some("0.43.3")
[opencv 0.43.3] === Environment configuration:
[opencv 0.43.3] ===   OPENCV_HEADER_DIR = None
[opencv 0.43.3] ===   OPENCV_PACKAGE_NAME = None
[opencv 0.43.3] ===   OPENCV_PKGCONFIG_NAME = None
[opencv 0.43.3] ===   OPENCV_CMAKE_NAME = None
[opencv 0.43.3] ===   OPENCV_CMAKE_BIN = None
[opencv 0.43.3] ===   OPENCV_VCPKG_NAME = None
[opencv 0.43.3] ===   OPENCV_LINK_LIBS = Some("/opt/intel/openvino_2021/opencv/lib")
[opencv 0.43.3] ===   OPENCV_LINK_PATHS = Some("/opt/intel/openvino_2021/opencv/lib")
[opencv 0.43.3] ===   OPENCV_INCLUDE_PATHS = Some("/opt/intel/openvino_2021/opencv/include")
[opencv 0.43.3] ===   OPENCV_DISABLE_PROBES = None
[opencv 0.43.3] ===   OPENCV_CLANG_STDLIB_PATH = None
[opencv 0.43.3] ===   CMAKE_PREFIX_PATH = None
[opencv 0.43.3] ===   OpenCV_DIR = Some("/opt/intel/openvino_2021/opencv/cmake")
[opencv 0.43.3] ===   PKG_CONFIG_PATH = Some("/opt/intel/openvino_2021/data_processing/dl_streamer/lib/pkgconfig:/opt/intel/openvino_2021/data_processing/gstreamer/lib/pkgconfig:")
[opencv 0.43.3] ===   VCPKG_ROOT = None
[opencv 0.43.3] === Enabled features:
[opencv 0.43.3] ===   BINDING_GENERATOR
[opencv 0.43.3] ===   BUILDTIME_BINDGEN
[opencv 0.43.3] ===   CLANG
[opencv 0.43.3] ===   DEFAULT
[opencv 0.43.3] ===   JOBSERVER
[opencv 0.43.3] ===   OPENCV_4
[opencv 0.43.3] === Configuring OpenCV library from the environment:
[opencv 0.43.3] ===   include_paths: /opt/intel/openvino_2021/opencv/include
[opencv 0.43.3] ===   link_paths: /opt/intel/openvino_2021/opencv/lib
[opencv 0.43.3] ===   link_libs: /opt/intel/openvino_2021/opencv/lib
[opencv 0.43.3] === OpenCV library configuration: Library {
[opencv 0.43.3]     include_paths: [
[opencv 0.43.3]         "/opt/intel/openvino_2021/opencv/include",
[opencv 0.43.3]     ],
[opencv 0.43.3]     version: "4.5.0",
[opencv 0.43.3]     cargo_metadata: [
[opencv 0.43.3]         "cargo:rustc-link-search=/opt/intel/openvino_2021/opencv/lib",
[opencv 0.43.3]         "cargo:rustc-link-lib=opencv",
[opencv 0.43.3]     ],
[opencv 0.43.3] }
[opencv 0.43.3] === Found OpenCV library version: 4.5.0 in headers located at: /opt/intel/openvino_2021/opencv/include
[opencv 0.43.3] === Using OpenCV headers from: /opt/intel/openvino_2021/opencv/include/opencv2
[opencv 0.43.3] === Generating code in: /home/bus710/repo/tmp/projects/rust_opencv/target/debug/build/opencv-3c59b05332037a20/out
[opencv 0.43.3] === Placing generated bindings into: /home/bus710/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.43.3/bindings/rust/opencv_4
[opencv 0.43.3] === Clang: clang version 10.0.0-4ubuntu1 
[opencv 0.43.3] thread 'main' panicked at 'Can't find clang binary', /home/bus710/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-binding-generator-0.16.2/src/generator.rs:339:68
[opencv 0.43.3] stack backtrace:
[opencv 0.43.3]    0:     0x55c42423ebd0 - std::backtrace_rs::backtrace::libunwind::trace::h577ea05e9ca4629a
[opencv 0.43.3]                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
[opencv 0.43.3]    1:     0x55c42423ebd0 - std::backtrace_rs::backtrace::trace_unsynchronized::h50b9b72b84c7dd56
[opencv 0.43.3]                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/../../backtrace/src/backtrace/mod.rs:66
[opencv 0.43.3]    2:     0x55c42423ebd0 - std::sys_common::backtrace::_print_fmt::h6541cf9823837fac
[opencv 0.43.3]                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:79
[opencv 0.43.3]    3:     0x55c42423ebd0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf64fbff071026df5
[opencv 0.43.3]                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:58
[opencv 0.43.3]    4:     0x55c424264bbc - core::fmt::write::h9ddafa4860d8adff
[opencv 0.43.3]                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/fmt/mod.rs:1082
[opencv 0.43.3]    5:     0x55c42423a5b7 - std::io::Write::write_fmt::h1d2ee292d2b65481
[opencv 0.43.3]                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/io/mod.rs:1514
[opencv 0.43.3]    6:     0x55c424241100 - std::sys_common::backtrace::_print::ha25f9ff5080d886d
[opencv 0.43.3]                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:61
[opencv 0.43.3]    7:     0x55c424241100 - std::sys_common::backtrace::print::h213e8aa8dc5405c0
[opencv 0.43.3]                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:48
[opencv 0.43.3]    8:     0x55c424241100 - std::panicking::default_hook::{{closure}}::h6482fae49ef9d963
[opencv 0.43.3]                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:200
[opencv 0.43.3]    9:     0x55c424240e4c - std::panicking::default_hook::he30ad7589e0970f9
[opencv 0.43.3]                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:219
[opencv 0.43.3]   10:     0x55c424241763 - std::panicking::rust_panic_with_hook::haa1ed36ada4ffb03
[opencv 0.43.3]                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:569
[opencv 0.43.3]   11:     0x55c424241339 - std::panicking::begin_panic_handler::{{closure}}::h7001af1bb21aeaeb
[opencv 0.43.3]                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:476
[opencv 0.43.3]   12:     0x55c42423f05c - std::sys_common::backtrace::__rust_end_short_backtrace::h39910f557f5f2367
[opencv 0.43.3]                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:153
[opencv 0.43.3]   13:     0x55c4242412f9 - rust_begin_unwind
[opencv 0.43.3]                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
[opencv 0.43.3]   14:     0x55c4242631c1 - core::panicking::panic_fmt::h4e2659771ebc78eb
[opencv 0.43.3]                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
[opencv 0.43.3]   15:     0x55c424262f53 - core::option::expect_failed::hd5a1da3a6b6bbb34
[opencv 0.43.3]                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/option.rs:1213
[opencv 0.43.3]   16:     0x55c423f0dbf0 - core::option::Option<T>::expect::h3dd7ed627352ea25
[opencv 0.43.3]                                at /home/bus710/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:333
[opencv 0.43.3]   17:     0x55c423f16b21 - opencv_binding_generator::generator::Generator::new::h9fec1910bd14c3c7
[opencv 0.43.3]                                at /home/bus710/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-binding-generator-0.16.2/src/generator.rs:339
[opencv 0.43.3]   18:     0x55c423d0468e - build_script_build::generator::gen_wrapper::h9ff0000e082a3a1e
[opencv 0.43.3]                                at /home/bus710/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.43.3/build.rs:166
[opencv 0.43.3]   19:     0x55c423d01add - build_script_build::main::h106629cfeeb55255
[opencv 0.43.3]                                at /home/bus710/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.43.3/build.rs:1137
[opencv 0.43.3]   20:     0x55c423d43d4b - core::ops::function::FnOnce::call_once::h7c5c19cc5741e3ff
[opencv 0.43.3]                                at /home/bus710/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
[opencv 0.43.3]   21:     0x55c423d3b2fe - std::sys_common::backtrace::__rust_begin_short_backtrace::h8fb3181da121a73c
[opencv 0.43.3]                                at /home/bus710/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137
[opencv 0.43.3]   22:     0x55c423d1ad71 - std::rt::lang_start::{{closure}}::ha37597204c586ff7
[opencv 0.43.3]                                at /home/bus710/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:66
[opencv 0.43.3]   23:     0x55c424241b61 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h6a3209f124be2235
[opencv 0.43.3]                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:259
[opencv 0.43.3]   24:     0x55c424241b61 - std::panicking::try::do_call::h88ce358792b64df0
[opencv 0.43.3]                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:373
[opencv 0.43.3]   25:     0x55c424241b61 - std::panicking::try::h6311c259678e50fc
[opencv 0.43.3]                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:337
[opencv 0.43.3]   26:     0x55c424241b61 - std::panic::catch_unwind::h56c5716807d659a1
[opencv 0.43.3]                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panic.rs:379
[opencv 0.43.3]   27:     0x55c424241b61 - std::rt::lang_start_internal::h73711f37ecfcb277
[opencv 0.43.3]                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/rt.rs:51
[opencv 0.43.3]   28:     0x55c423d1ad47 - std::rt::lang_start::ha37942e742db5fd0
[opencv 0.43.3]                                at /home/bus710/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:65
[opencv 0.43.3]   29:     0x55c423d02b9a - main
[opencv 0.43.3]   30:     0x7ff9172e80b3 - __libc_start_main
[opencv 0.43.3]   31:     0x55c423cf20ce - _start
[opencv 0.43.3]   32:                0x0 - <unknown>
error: failed to run custom build command for `opencv v0.43.3`

Caused by:
  process didn't exit successfully: `/home/bus710/repo/tmp/projects/rust_opencv/target/debug/build/opencv-16807245944feb34/build-script-build` (exit code: 101)
  --- stdout
  === Clang: clang version 10.0.0-4ubuntu1 

  --- stderr
  === Crate version: Some("0.43.3")
  === Environment configuration:
  ===   OPENCV_HEADER_DIR = None
  ===   OPENCV_PACKAGE_NAME = None
  ===   OPENCV_PKGCONFIG_NAME = None
  ===   OPENCV_CMAKE_NAME = None
  ===   OPENCV_CMAKE_BIN = None
  ===   OPENCV_VCPKG_NAME = None
  ===   OPENCV_LINK_LIBS = Some("/opt/intel/openvino_2021/opencv/lib")
  ===   OPENCV_LINK_PATHS = Some("/opt/intel/openvino_2021/opencv/lib")
  ===   OPENCV_INCLUDE_PATHS = Some("/opt/intel/openvino_2021/opencv/include")
  ===   OPENCV_DISABLE_PROBES = None
  ===   OPENCV_CLANG_STDLIB_PATH = None
  ===   CMAKE_PREFIX_PATH = None
  ===   OpenCV_DIR = Some("/opt/intel/openvino_2021/opencv/cmake")
  ===   PKG_CONFIG_PATH = Some("/opt/intel/openvino_2021/data_processing/dl_streamer/lib/pkgconfig:/opt/intel/openvino_2021/data_processing/gstreamer/lib/pkgconfig:")
  ===   VCPKG_ROOT = None
  === Enabled features:
  ===   BINDING_GENERATOR
  ===   BUILDTIME_BINDGEN
  ===   CLANG
  ===   DEFAULT
  ===   JOBSERVER
  ===   OPENCV_4
  === Configuring OpenCV library from the environment:
  ===   include_paths: /opt/intel/openvino_2021/opencv/include
  ===   link_paths: /opt/intel/openvino_2021/opencv/lib
  ===   link_libs: /opt/intel/openvino_2021/opencv/lib
  === OpenCV library configuration: Library {
      include_paths: [
          "/opt/intel/openvino_2021/opencv/include",
      ],
      version: "4.5.0",
      cargo_metadata: [
          "cargo:rustc-link-search=/opt/intel/openvino_2021/opencv/lib",
          "cargo:rustc-link-lib=opencv",
      ],
  }
  === Found OpenCV library version: 4.5.0 in headers located at: /opt/intel/openvino_2021/opencv/include
  === Using OpenCV headers from: /opt/intel/openvino_2021/opencv/include/opencv2
  === Generating code in: /home/bus710/repo/tmp/projects/rust_opencv/target/debug/build/opencv-3c59b05332037a20/out
  === Placing generated bindings into: /home/bus710/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.43.3/bindings/rust/opencv_4
  thread 'main' panicked at 'Can't find clang binary', /home/bus710/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-binding-generator-0.16.2/src/generator.rs:339:68
  stack backtrace:
     0:     0x55c42423ebd0 - std::backtrace_rs::backtrace::libunwind::trace::h577ea05e9ca4629a
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
     1:     0x55c42423ebd0 - std::backtrace_rs::backtrace::trace_unsynchronized::h50b9b72b84c7dd56
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/../../backtrace/src/backtrace/mod.rs:66
     2:     0x55c42423ebd0 - std::sys_common::backtrace::_print_fmt::h6541cf9823837fac
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:79
     3:     0x55c42423ebd0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf64fbff071026df5
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:58
     4:     0x55c424264bbc - core::fmt::write::h9ddafa4860d8adff
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/fmt/mod.rs:1082
     5:     0x55c42423a5b7 - std::io::Write::write_fmt::h1d2ee292d2b65481
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/io/mod.rs:1514
     6:     0x55c424241100 - std::sys_common::backtrace::_print::ha25f9ff5080d886d
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:61
     7:     0x55c424241100 - std::sys_common::backtrace::print::h213e8aa8dc5405c0
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:48
     8:     0x55c424241100 - std::panicking::default_hook::{{closure}}::h6482fae49ef9d963
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:200
     9:     0x55c424240e4c - std::panicking::default_hook::he30ad7589e0970f9
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:219
    10:     0x55c424241763 - std::panicking::rust_panic_with_hook::haa1ed36ada4ffb03
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:569
    11:     0x55c424241339 - std::panicking::begin_panic_handler::{{closure}}::h7001af1bb21aeaeb
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:476
    12:     0x55c42423f05c - std::sys_common::backtrace::__rust_end_short_backtrace::h39910f557f5f2367
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:153
    13:     0x55c4242412f9 - rust_begin_unwind
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
    14:     0x55c4242631c1 - core::panicking::panic_fmt::h4e2659771ebc78eb
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
    15:     0x55c424262f53 - core::option::expect_failed::hd5a1da3a6b6bbb34
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/option.rs:1213
    16:     0x55c423f0dbf0 - core::option::Option<T>::expect::h3dd7ed627352ea25
                                 at /home/bus710/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:333
    17:     0x55c423f16b21 - opencv_binding_generator::generator::Generator::new::h9fec1910bd14c3c7
                                 at /home/bus710/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-binding-generator-0.16.2/src/generator.rs:339
    18:     0x55c423d0468e - build_script_build::generator::gen_wrapper::h9ff0000e082a3a1e
                                 at /home/bus710/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.43.3/build.rs:166
    19:     0x55c423d01add - build_script_build::main::h106629cfeeb55255
                                 at /home/bus710/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.43.3/build.rs:1137
    20:     0x55c423d43d4b - core::ops::function::FnOnce::call_once::h7c5c19cc5741e3ff
                                 at /home/bus710/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
    21:     0x55c423d3b2fe - std::sys_common::backtrace::__rust_begin_short_backtrace::h8fb3181da121a73c
                                 at /home/bus710/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137
    22:     0x55c423d1ad71 - std::rt::lang_start::{{closure}}::ha37597204c586ff7
                                 at /home/bus710/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:66
    23:     0x55c424241b61 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h6a3209f124be2235
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:259
    24:     0x55c424241b61 - std::panicking::try::do_call::h88ce358792b64df0
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:373
    25:     0x55c424241b61 - std::panicking::try::h6311c259678e50fc
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:337
    26:     0x55c424241b61 - std::panic::catch_unwind::h56c5716807d659a1
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panic.rs:379
    27:     0x55c424241b61 - std::rt::lang_start_internal::h73711f37ecfcb277
                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/rt.rs:51
    28:     0x55c423d1ad47 - std::rt::lang_start::ha37942e742db5fd0
                                 at /home/bus710/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:65
    29:     0x55c423d02b9a - main
    30:     0x7ff9172e80b3 - __libc_start_main
    31:     0x55c423cf20ce - _start
    32:                0x0 - <unknown>
```

Please let me know if there is anything else I can add more! 
Thanks,

**Comment by twistedfall** [comment]
Hi, you appear to have some problem with llvm/clang installation, how did you install it? The problem seems to be that `libclang.so` is available, but the `clang` binary for some reason is not.

**Comment by bus710** [comment]
That is my fault. 
Previously I only installed libclang-dev because I thought the dev package might come with clang bin.

So I installed both for a new system with Ubuntu 20.04 and OpenVino 2021_1:
```sh
$ sudo apt install clang libclang-dev
$ sudo apt install cmake ninja-build # if needed
```

Then, I could successfully build a project powered by opencv-rust and OpenCV of OpenVino.

Thanks for your help!
