### ISSUE TITLE
Build always fail when building with `tfilte` crate, separate build each one if fine!

### ISSUE THREAD

**Issue by wisonye** [twistedfall/opencv-rust#182]
I'm building a project that needs `opencv` and `tflite` both work together. But I can't build the program when putting two of them into the same project. 

Title             | Description
------------ | ---------
OS                | MacO Mojave
Rust version| `rustc 1.47.0 (18bf6b4f0 2020-10-07)`
OpenCV       | The way to insatll: `brew install opencv`</br>location: **/usr/local/Cellar/opencv/4.5.0_2/**
$DYLD_LIBRARY_PATH | It doesn't set.
$DYLD_FALLBACK_LIBRARY_PATH | **/Library/Developer/CommandLineTools/usr/lib**
ls -lht $DYLD_FALLBACK_LIBRARY_PATH/libclang.dylib | **/Library/Developer/CommandLineTools/usr/lib/libclang.dylib**
Error             |   _thread 'main' panicked at 'a `libclang` shared library is not loaded on this thread', /Users/wison/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-1.0.3/src/lib.rs:1672:1_

## How to reproduce

It's super easy:

```bash
# Just create a blank new project
cargo new test-opencv-and-tfilte-build-together
cd test-opencv-and-tfilte-build-together/

# And then put both dependencies there
vim Cargo.toml
```

Here is the **Cargo.toml** content:

```
[package]
name = "test-opencv-and-tfilte-build-together"
version = "0.1.0"
authors = ["“WisonYe” <wisonye@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.46"
tflite = "0.9.2"
```

Then build it and you will see the error, below is the entire `cargo build`output:

```
   Updating crates.io index
   Compiling libc v0.2.80
   Compiling memchr v2.3.4
   Compiling lazy_static v1.4.0
   Compiling proc-macro2 v1.0.24
   Compiling glob v0.3.0
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.52
   Compiling cfg-if v1.0.0
   Compiling regex-syntax v0.6.21
   Compiling version_check v0.9.2
   Compiling shlex v0.1.1
   Compiling log v0.4.11
   Compiling bitflags v1.2.1
   Compiling unicode-width v0.1.8
   Compiling cfg-if v0.1.10
   Compiling quick-error v1.2.3
   Compiling vec_map v0.8.2
   Compiling strsim v0.8.0
   Compiling if_rust_version v1.0.0
   Compiling termcolor v1.1.2
   Compiling bindgen v0.55.1
   Compiling ansi_term v0.11.0
   Compiling byteorder v1.3.4
   Compiling once_cell v1.5.2
   Compiling dunce v1.0.1
   Compiling percent-encoding v2.1.0
   Compiling lazycell v1.3.0
   Compiling peeking_take_while v0.1.2
   Compiling semver-parser v0.7.0
   Compiling rustc-hash v1.1.0
   Compiling autocfg v1.0.1
   Compiling maplit v1.0.2
   Compiling pkg-config v0.3.19
   Compiling fs_extra v1.2.0
   Compiling vcpkg v0.2.10
   Compiling maybe-owned v0.3.4
   Compiling thread_local v1.0.1
   Compiling libloading v0.6.5
   Compiling textwrap v0.11.0
   Compiling humantime v1.3.0
   Compiling clang-sys v1.0.3
   Compiling nom v5.1.2
   Compiling semver v0.10.0
   Compiling num-traits v0.2.14
   Compiling aho-corasick v0.7.15
   Compiling jobserver v0.1.21
   Compiling atty v0.2.14
   Compiling which v3.1.1
   Compiling quote v1.0.7
   Compiling cc v1.0.65
   Compiling clap v2.33.3
   Compiling regex v1.4.2
   Compiling clang v1.0.2
   Compiling cexpr v0.4.0
   Compiling env_logger v0.7.1
   Compiling opencv-binding-generator v0.21.3
   Compiling cpp_common v0.5.5
   Compiling cpp_build v0.5.5
   Compiling opencv v0.46.3
   Compiling cpp_macros v0.5.5
   Compiling thiserror-impl v1.0.22
   Compiling tflite v0.9.3
   Compiling cpp v0.5.5
error: failed to run custom build command for `opencv v0.46.3`

Caused by:
  process didn't exit successfully: `/Users/wison/temp/test-opencv-and-tfilte-build-together/target/debug/build/opencv-a2a3f744a20ca410/build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=OPENCV4_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=OPENCV4_STATIC
  cargo:rerun-if-env-changed=OPENCV4_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=OPENCV4_STATIC
  cargo:rerun-if-env-changed=OPENCV4_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=OPENCV4_STATIC
  cargo:rerun-if-env-changed=OPENCV4_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  === Crate version: Some("0.46.3")
  === Environment configuration:
  ===   OPENCV_HEADER_DIR = None
  ===   OPENCV_PACKAGE_NAME = None
  ===   OPENCV_PKGCONFIG_NAME = None
  ===   OPENCV_CMAKE_NAME = None
  ===   OPENCV_CMAKE_BIN = None
  ===   OPENCV_VCPKG_NAME = None
  ===   OPENCV_LINK_LIBS = None
  ===   OPENCV_LINK_PATHS = None
  ===   OPENCV_INCLUDE_PATHS = None
  ===   OPENCV_DISABLE_PROBES = None
  ===   OPENCV_CLANG_STDLIB_PATH = None
  ===   OPENCV_MODULE_WHITELIST = None
  ===   OPENCV_MODULE_BLACKLIST = None
  ===   CMAKE_PREFIX_PATH = None
  ===   OpenCV_DIR = None
  ===   PKG_CONFIG_PATH = None
  ===   VCPKG_ROOT = None
  ===   VCPKGRS_DYNAMIC = None
  === Enabled features:
  ===   BINDING_GENERATOR
  ===   BUILDTIME_BINDGEN
  ===   CLANG
  ===   DEFAULT
  ===   JOBSERVER
  ===   OPENCV_4
  === Detected probe priority based on environment vars: pkg_config: false, cmake: false, vcpkg: false
  === Probing the OpenCV library in the following order: environment, pkg_config, cmake, vcpkg_cmake, vcpkg
  === Can't probe using: environment, continuing with other methods because: Some environment variables are missing
  === Probing OpenCV library using pkg_config
  === OpenCV library configuration: Library {
      include_paths: [
          "/usr/local/Cellar/opencv/4.5.0_2/include/opencv4",
      ],
      version: "4.5.0",
      cargo_metadata: [
          "cargo:rustc-link-search=/usr/local/Cellar/opencv/4.5.0_2/lib",
          "cargo:rustc-link-search=framework=/usr/local/Cellar/opencv/4.5.0_2/lib",
          "cargo:rustc-link-lib=opencv_gapi",
          "cargo:rustc-link-lib=opencv_stitching",
          "cargo:rustc-link-lib=opencv_alphamat",
          "cargo:rustc-link-lib=opencv_aruco",
          "cargo:rustc-link-lib=opencv_bgsegm",
          "cargo:rustc-link-lib=opencv_bioinspired",
          "cargo:rustc-link-lib=opencv_ccalib",
          "cargo:rustc-link-lib=opencv_dnn_objdetect",
          "cargo:rustc-link-lib=opencv_dnn_superres",
          "cargo:rustc-link-lib=opencv_dpm",
          "cargo:rustc-link-lib=opencv_highgui",
          "cargo:rustc-link-lib=opencv_face",
          "cargo:rustc-link-lib=opencv_freetype",
          "cargo:rustc-link-lib=opencv_fuzzy",
          "cargo:rustc-link-lib=opencv_hfs",
          "cargo:rustc-link-lib=opencv_img_hash",
          "cargo:rustc-link-lib=opencv_intensity_transform",
          "cargo:rustc-link-lib=opencv_line_descriptor",
          "cargo:rustc-link-lib=opencv_mcc",
          "cargo:rustc-link-lib=opencv_quality",
          "cargo:rustc-link-lib=opencv_rapid",
          "cargo:rustc-link-lib=opencv_reg",
          "cargo:rustc-link-lib=opencv_rgbd",
          "cargo:rustc-link-lib=opencv_saliency",
          "cargo:rustc-link-lib=opencv_sfm",
          "cargo:rustc-link-lib=opencv_stereo",
          "cargo:rustc-link-lib=opencv_structured_light",
          "cargo:rustc-link-lib=opencv_phase_unwrapping",
          "cargo:rustc-link-lib=opencv_superres",
          "cargo:rustc-link-lib=opencv_optflow",
          "cargo:rustc-link-lib=opencv_surface_matching",
          "cargo:rustc-link-lib=opencv_tracking",
          "cargo:rustc-link-lib=opencv_datasets",
          "cargo:rustc-link-lib=opencv_text",
          "cargo:rustc-link-lib=opencv_dnn",
          "cargo:rustc-link-lib=opencv_plot",
          "cargo:rustc-link-lib=opencv_videostab",
          "cargo:rustc-link-lib=opencv_videoio",
          "cargo:rustc-link-lib=opencv_viz",
          "cargo:rustc-link-lib=opencv_xfeatures2d",
          "cargo:rustc-link-lib=opencv_shape",
          "cargo:rustc-link-lib=opencv_ml",
          "cargo:rustc-link-lib=opencv_ximgproc",
          "cargo:rustc-link-lib=opencv_video",
          "cargo:rustc-link-lib=opencv_xobjdetect",
          "cargo:rustc-link-lib=opencv_objdetect",
          "cargo:rustc-link-lib=opencv_calib3d",
          "cargo:rustc-link-lib=opencv_imgcodecs",
          "cargo:rustc-link-lib=opencv_features2d",
          "cargo:rustc-link-lib=opencv_flann",
          "cargo:rustc-link-lib=opencv_xphoto",
          "cargo:rustc-link-lib=opencv_photo",
          "cargo:rustc-link-lib=opencv_imgproc",
          "cargo:rustc-link-lib=opencv_core",
      ],
  }
  === Found OpenCV library version: 4.5.0 in headers located at: /usr/local/Cellar/opencv/4.5.0_2/include/opencv4
  === Using OpenCV headers from: /usr/local/Cellar/opencv/4.5.0_2/include/opencv4/opencv2
  === Generating code in: /Users/wison/temp/test-opencv-and-tfilte-build-together/target/debug/build/opencv-3904f7d25110ecf3/out
  === Placing generated bindings into: /Users/wison/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.46.3/bindings/rust/opencv_4
  thread 'main' panicked at 'a `libclang` shared library is not loaded on this thread', /Users/wison/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-1.0.3/src/lib.rs:1672:1
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

And then I open the **/Users/wison/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-1.0.3/src/lib.rs** and locate to **1672** line to see what's going on there, I got nothing useful:

<img width="826" alt="1672-line" src="https://user-images.githubusercontent.com/3477321/100527314-45774800-3236-11eb-84e8-789b591aefcf.png">

</hr>

Again, the `opencv` and `tflite` both build successfully if they're in different rust project, only got the error above when they put together into the same project (even nested crate like what I'm doing in my project). Here is my rust project structure:

<img width="2164" alt="my-project-structure" src="https://user-images.githubusercontent.com/3477321/100527471-9dfb1500-3237-11eb-9e0b-7b7c0dcfa827.png">

It's very urgent, plz help :)

**Comment by twistedfall** [comment]
Did you try building with `clang-runtime` feature enabled?

**Comment by wisonye** [comment]
@twistedfall If you mean like below, then it works:

```
[dependencies]
opencv = { version = "0.46", features = ["clang-runtime"] }
tflite = "0.9.2"
```

But just want to confirm that:

It still enable the `opencv-4`feature and `buildtime-bindgen` feature, as I didn't put `default-features = false` there, right?

Also, I will confirm that works or not on my project after lunch, I will update the result, thanks for your help :)

**Comment by wisonye** [comment]
I confirmed that focus on the error **'a libclang shared library is not loaded on this thread'**,  this is the correct fixed:

```
opencv = { version = "0.46", features = ["clang-runtime"] }
```

<img width="1098" alt="Screen Shot 2020-11-29 at 1 47 20 PM" src="https://user-images.githubusercontent.com/3477321/100529235-2e425580-324a-11eb-86ee-2b6e651dacef.png">

I think that's why the error comes:)

@twistedfall But before you close this issue, if possible,  I just wonder what the main difference between **Dynamically linking** and **runtime feature (clang_sys::load)**? As for my understanding, they both load the `libclang` shared library (`libclang.so` on Linux, `libclang.dylib` on macOS, `libclang.dll` on Windows) when the program runs, or my I made a mistake on that?

**Comment by twistedfall** [comment]
> It still enable the `opencv-4`feature and `buildtime-bindgen` feature, as I didn't put `default-features = false` there, right?

That’s correct.

> what the main difference between **Dynamically linking** and **runtime feature (clang_sys::load)**

As far as I remember for `clang-sys` dynamic linking relies on your system linker to do the job, and runtime uses dlopen to load libclang. In this case the difference doesn’t really matter, the problem is that `bindgen` crate (a dependency of `tfilte`) depends on `clang-sys` with hard-enabled `runtime` feature and because of that cargo makes this feature also enabled for every crate that depends on `clang-sys`. `opencv` crates tries to use multiple threads to generate modules and `clang-sys` with `runtime` doesn't like that (hence the panic). That's why we need to use a different approach to parallelize the build. When you use `clang-runtime` feature the crate uses multiple processes instead of multiple threads.

**Comment by wisonye** [comment]
> > It still enable the `opencv-4`feature and `buildtime-bindgen` feature, as I didn't put `default-features = false` there, right?
> 
> That’s correct.
> 
> > what the main difference between **Dynamically linking** and **runtime feature (clang_sys::load)**
> 
> As far as I remember for `clang-sys` dynamic linking relies on your system linker to do the job, and runtime uses dlopen to load libclang. In this case the difference doesn’t really matter, the problem is that `bindgen` crate (a dependency of `tfilte`) depends on `clang-sys` with hard-enabled `runtime` feature and because of that cargo makes this feature also enabled for every crate that depends on `clang-sys`. `opencv` crates tries to use multiple threads to generate modules and `clang-sys` with `runtime` doesn't like that (hence the panic). That's why we need to use a different approach to parallelize the build. When you use `clang-runtime` feature the crate uses multiple processes instead of multiple threads.

@twistedfall That's a very clear explanation, thank you so much!! 👍
