### ISSUE TITLE
Unable to build on Ubuntu 18.04 

### ISSUE THREAD

**Issue by theunkn0wn1** [twistedfall/opencv-rust#188]
Before reporting an issue please first check the
[troubleshooting guide](https://github.com/twistedfall/opencv-rust/blob/master/README.md#troubleshooting). If
the issue you're encountering is not solved thereby please state the following in your bugreport:
1. Operating system
```
$ lsb_release -a
LSB Version:	core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

```

2. The way you installed OpenCV: package, official binary distribution, manual compilation, etc.
Installed via package manager

3. OpenCV version
`3.2`
4. rustc version (`rustc --version`)
```
$ rustc --version
rustc 1.48.0 (7eac88abb 2020-11-16)
```

5. Attach the full output of the following command from your project directory:
```
$ RUST_BACKTRACE=full cargo build -vv
       Fresh glob v0.3.0
       Fresh lazy_static v1.4.0
       Fresh regex-syntax v0.6.21
       Fresh semver-parser v0.7.0
       Fresh maplit v1.0.2
       Fresh dunce v1.0.1
       Fresh autocfg v1.0.1
       Fresh once_cell v1.5.2
       Fresh percent-encoding v2.1.0
       Fresh shlex v0.1.1
       Fresh vcpkg v0.2.11
       Fresh pkg-config v0.3.19
       Fresh thread_local v1.0.1
       Fresh semver v0.10.0
       Fresh libc v0.2.81
       Fresh memchr v2.3.4
       Fresh jobserver v0.1.21
       Fresh clang-sys v1.0.3
       Fresh aho-corasick v0.7.15
       Fresh cc v1.0.66
       Fresh clang v1.0.3
   Compiling num-traits v0.2.14
       Fresh regex v1.4.2
     Running `CARGO=/home/orion/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo CARGO_CRATE_NAME=num_traits CARGO_MANIFEST_DIR=/home/orion/.cargo/registry/src/github.com-1ecc6299db9ec823/num-traits-0.2.14 CARGO_PKG_AUTHORS='The Rust Project Developers' CARGO_PKG_DESCRIPTION='Numeric traits for generic mathematics' CARGO_PKG_HOMEPAGE='https://github.com/rust-num/num-traits' CARGO_PKG_LICENSE='MIT OR Apache-2.0' CARGO_PKG_LICENSE_FILE='' CARGO_PKG_NAME=num-traits CARGO_PKG_REPOSITORY='https://github.com/rust-num/num-traits' CARGO_PKG_VERSION=0.2.14 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=2 CARGO_PKG_VERSION_PATCH=14 CARGO_PKG_VERSION_PRE='' LD_LIBRARY_PATH='/home/orion/projects/skool/rover/experiments/cv-experiments/target/debug/deps:/home/orion/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib:/home/orion/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib' OUT_DIR=/home/orion/projects/skool/rover/experiments/cv-experiments/target/debug/build/num-traits-525b6fecdd3a42f1/out rustc --crate-name num_traits /home/orion/.cargo/registry/src/github.com-1ecc6299db9ec823/num-traits-0.2.14/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=ec7a39eee29a6869 -C extra-filename=-ec7a39eee29a6869 --out-dir /home/orion/projects/skool/rover/experiments/cv-experiments/target/debug/deps -L dependency=/home/orion/projects/skool/rover/experiments/cv-experiments/target/debug/deps --cap-lints warn --cfg has_i128 --cfg has_to_int_unchecked`
       Fresh opencv-binding-generator v0.21.3
   Compiling opencv v0.46.3
     Running `/home/orion/projects/skool/rover/experiments/cv-experiments/target/debug/build/opencv-c31b1e450f8c0ddd/build-script-build`
[opencv 0.46.3] thread 'main' panicked at 'Please select exactly one of the features: opencv-32, opencv-34, opencv-4', /home/orion/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.46.3/build.rs:812:9
[opencv 0.46.3] stack backtrace:
[opencv 0.46.3]    0:     0x5632c41eef30 - std::backtrace_rs::backtrace::libunwind::trace::h72c2fb8038f1bbee
[opencv 0.46.3]                                at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
[opencv 0.46.3]    1:     0x5632c41eef30 - std::backtrace_rs::backtrace::trace_unsynchronized::h1e3b084883f1e78c
[opencv 0.46.3]                                at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
[opencv 0.46.3]    2:     0x5632c41eef30 - std::sys_common::backtrace::_print_fmt::h3bf6a7ebf7f0394a
[opencv 0.46.3]                                at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
[opencv 0.46.3]    3:     0x5632c41eef30 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2e8cb764b7fe02e7
[opencv 0.46.3]                                at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58
[opencv 0.46.3]    4:     0x5632c42147bc - core::fmt::write::h7a1184eaee6a8644
[opencv 0.46.3]                                at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
[opencv 0.46.3]    5:     0x5632c41ea502 - std::io::Write::write_fmt::haeeb374d93a67eac
[opencv 0.46.3]                                at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516
[opencv 0.46.3]    6:     0x5632c41f18ad - std::sys_common::backtrace::_print::h1d14a7f6ad632dc8
[opencv 0.46.3]                                at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61
[opencv 0.46.3]    7:     0x5632c41f18ad - std::sys_common::backtrace::print::h301abac8bb2e3e81
[opencv 0.46.3]                                at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48
[opencv 0.46.3]    8:     0x5632c41f18ad - std::panicking::default_hook::{{closure}}::hde0cb80358a6920a
[opencv 0.46.3]                                at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208
[opencv 0.46.3]    9:     0x5632c41f1558 - std::panicking::default_hook::h9b1a691049a0ec8f
[opencv 0.46.3]                                at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:227
[opencv 0.46.3]   10:     0x5632c41f1f91 - std::panicking::rust_panic_with_hook::h2bdec87b60580584
[opencv 0.46.3]                                at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:577
[opencv 0.46.3]   11:     0x5632c41becec - std::panicking::begin_panic::{{closure}}::ha7c18aba4a638a5d
[opencv 0.46.3]                                at /home/orion/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:506
[opencv 0.46.3]   12:     0x5632c41beb29 - std::sys_common::backtrace::__rust_end_short_backtrace::hacf1d5b023067432
[opencv 0.46.3]                                at /home/orion/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:153
[opencv 0.46.3]   13:     0x5632c41bec17 - std::panicking::begin_panic::h97a52fa135e13718
[opencv 0.46.3]                                at /home/orion/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:505
[opencv 0.46.3]   14:     0x5632c3c9ab6f - build_script_build::main::h41aee4f15692980a
[opencv 0.46.3]                                at /home/orion/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.46.3/build.rs:812
[opencv 0.46.3]   15:     0x5632c3cad1fb - core::ops::function::FnOnce::call_once::hd9459395910fd7dc
[opencv 0.46.3]                                at /home/orion/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
[opencv 0.46.3]   16:     0x5632c3cbc2ee - std::sys_common::backtrace::__rust_begin_short_backtrace::h2eeb935cc40afa55
[opencv 0.46.3]                                at /home/orion/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137
[opencv 0.46.3]   17:     0x5632c3cd4821 - std::rt::lang_start::{{closure}}::hdb0dc65f8266f64e
[opencv 0.46.3]                                at /home/orion/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:66
[opencv 0.46.3]   18:     0x5632c41f23b7 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::he179d32a5d10d957
[opencv 0.46.3]                                at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:259
[opencv 0.46.3]   19:     0x5632c41f23b7 - std::panicking::try::do_call::hcb3d5e7be089b2b4
[opencv 0.46.3]                                at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:381
[opencv 0.46.3]   20:     0x5632c41f23b7 - std::panicking::try::h7ac93b0cd56fb701
[opencv 0.46.3]                                at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:345
[opencv 0.46.3]   21:     0x5632c41f23b7 - std::panic::catch_unwind::h7b40e396c93a4fcd
[opencv 0.46.3]                                at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panic.rs:382
[opencv 0.46.3]   22:     0x5632c41f23b7 - std::rt::lang_start_internal::h142b9cc66267fea1
[opencv 0.46.3]                                at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/rt.rs:51
[opencv 0.46.3]   23:     0x5632c3cd47f7 - std::rt::lang_start::h93c0db1186f17374
[opencv 0.46.3]                                at /home/orion/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:65
[opencv 0.46.3]   24:     0x5632c3c9ceda - main
[opencv 0.46.3]   25:     0x7f3c6d305bf7 - __libc_start_main
[opencv 0.46.3]   26:     0x5632c3c8a9fa - _start
[opencv 0.46.3]   27:                0x0 - <unknown>
error: failed to run custom build command for `opencv v0.46.3`

Caused by:
  process didn't exit successfully: `/home/orion/projects/skool/rover/experiments/cv-experiments/target/debug/build/opencv-c31b1e450f8c0ddd/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'Please select exactly one of the features: opencv-32, opencv-34, opencv-4', /home/orion/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.46.3/build.rs:812:9
  stack backtrace:
     0:     0x5632c41eef30 - std::backtrace_rs::backtrace::libunwind::trace::h72c2fb8038f1bbee
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
     1:     0x5632c41eef30 - std::backtrace_rs::backtrace::trace_unsynchronized::h1e3b084883f1e78c
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
     2:     0x5632c41eef30 - std::sys_common::backtrace::_print_fmt::h3bf6a7ebf7f0394a
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
     3:     0x5632c41eef30 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2e8cb764b7fe02e7
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58
     4:     0x5632c42147bc - core::fmt::write::h7a1184eaee6a8644
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
     5:     0x5632c41ea502 - std::io::Write::write_fmt::haeeb374d93a67eac
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516
     6:     0x5632c41f18ad - std::sys_common::backtrace::_print::h1d14a7f6ad632dc8
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61
     7:     0x5632c41f18ad - std::sys_common::backtrace::print::h301abac8bb2e3e81
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48
     8:     0x5632c41f18ad - std::panicking::default_hook::{{closure}}::hde0cb80358a6920a
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208
     9:     0x5632c41f1558 - std::panicking::default_hook::h9b1a691049a0ec8f
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:227
    10:     0x5632c41f1f91 - std::panicking::rust_panic_with_hook::h2bdec87b60580584
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:577
    11:     0x5632c41becec - std::panicking::begin_panic::{{closure}}::ha7c18aba4a638a5d
                                 at /home/orion/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:506
    12:     0x5632c41beb29 - std::sys_common::backtrace::__rust_end_short_backtrace::hacf1d5b023067432
                                 at /home/orion/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:153
    13:     0x5632c41bec17 - std::panicking::begin_panic::h97a52fa135e13718
                                 at /home/orion/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:505
    14:     0x5632c3c9ab6f - build_script_build::main::h41aee4f15692980a
                                 at /home/orion/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.46.3/build.rs:812
    15:     0x5632c3cad1fb - core::ops::function::FnOnce::call_once::hd9459395910fd7dc
                                 at /home/orion/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
    16:     0x5632c3cbc2ee - std::sys_common::backtrace::__rust_begin_short_backtrace::h2eeb935cc40afa55
                                 at /home/orion/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137
    17:     0x5632c3cd4821 - std::rt::lang_start::{{closure}}::hdb0dc65f8266f64e
                                 at /home/orion/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:66
    18:     0x5632c41f23b7 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::he179d32a5d10d957
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:259
    19:     0x5632c41f23b7 - std::panicking::try::do_call::hcb3d5e7be089b2b4
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:381
    20:     0x5632c41f23b7 - std::panicking::try::h7ac93b0cd56fb701
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:345
    21:     0x5632c41f23b7 - std::panic::catch_unwind::h7b40e396c93a4fcd
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panic.rs:382
    22:     0x5632c41f23b7 - std::rt::lang_start_internal::h142b9cc66267fea1
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/rt.rs:51
    23:     0x5632c3cd47f7 - std::rt::lang_start::h93c0db1186f17374
                                 at /home/orion/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:65
    24:     0x5632c3c9ceda - main
    25:     0x7f3c6d305bf7 - __libc_start_main
    26:     0x5632c3c8a9fa - _start
    27:                0x0 - <unknown>
warning: build failed, waiting for other jobs to finish...
error: build failed
```

Additional: 
the project itself is blank `cargo new` and here is the contents of the `cargo.toml`
```toml
$ cat Cargo.toml 
[package]
name = "cv-experiments"
version = "0.1.0"
authors = ["Joshua Salzedo <thhunkn0wnd@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.opencv]
version="0.46.3"
features = ["opencv-32", "buildtime-bindgen"]
```

**Comment by twistedfall** [comment]
Use `default-features = false` in your Cargo.toml. opencv-4 is enabled by default and you're enabling opencv-32 in addition to that, only one of those must be enabled at the time.

**Comment by theunkn0wn1** [comment]
> Use `default-features = false` in your Cargo.toml. opencv-4 is enabled by default and you're enabling opencv-32 in addition to that, only one of those must be enabled at the time.

That did the trick. thanks. :facepalm:
