### ISSUE TITLE
Unable to cargo build on macOS despite setting DYLD_FALLBACK_LIBRARY_PATH

### ISSUE THREAD

**Issue by dllu** [twistedfall/opencv-rust#205]
I have followed the README pefectly with `brew install opencv`, setting up xcode command line tools correctly, and so on.

In particular I must stress that I have in fact read item 6 of the troubleshooting guide and have set the `DYLD_FALLBACK_LIBRARY_PATH` as indicated there.

On macOS 11.0 big sur.

The full log is pretty long but all the errors are basically the same, here's the tail of the errors:

```
  === Running binding generator binary: "/Users/dllu/tempus/av-service/target/debug/build/opencv-11c85100c2c87d4b/out/release/binding-generator" "/usr/local/Cellar/opencv/4.5.0_2/include/opencv4" "/Users/dllu/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.48.0/src_cpp" "/Users/dllu/tempus/av-service/target/debug/build/opencv-11c85100c2c87d4b/out" "xfeatures2d" "4.3.0" "None"
  dyld: Library not loaded: @rpath/libclang.dylib
    Referenced from: /Users/dllu/tempus/av-service/target/debug/build/opencv-11c85100c2c87d4b/out/release/binding-generator
    Reason: image not found
  thread '<unnamed>' panicked at 'Failed to run the bindings generator', /Users/dllu/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.48.0/build_generator.rs:127:25
  === Running binding generator binary: "/Users/dllu/tempus/av-service/target/debug/build/opencv-11c85100c2c87d4b/out/release/binding-generator" "/usr/local/Cellar/opencv/4.5.0_2/include/opencv4" "/Users/dllu/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.48.0/src_cpp" "/Users/dllu/tempus/av-service/target/debug/build/opencv-11c85100c2c87d4b/out" "ximgproc" "4.3.0" "None"
  dyld: Library not loaded: @rpath/libclang.dylib
    Referenced from: /Users/dllu/tempus/av-service/target/debug/build/opencv-11c85100c2c87d4b/out/release/binding-generator
    Reason: image not found
  thread '<unnamed>' panicked at 'Failed to run the bindings generator', /Users/dllu/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.48.0/build_generator.rs:127:25
  === Running binding generator binary: "/Users/dllu/tempus/av-service/target/debug/build/opencv-11c85100c2c87d4b/out/release/binding-generator" "/usr/local/Cellar/opencv/4.5.0_2/include/opencv4" "/Users/dllu/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.48.0/src_cpp" "/Users/dllu/tempus/av-service/target/debug/build/opencv-11c85100c2c87d4b/out" "xobjdetect" "4.3.0" "None"
  dyld: Library not loaded: @rpath/libclang.dylib
    Referenced from: /Users/dllu/tempus/av-service/target/debug/build/opencv-11c85100c2c87d4b/out/release/binding-generator
    Reason: image not found
  thread '<unnamed>' panicked at 'Failed to run the bindings generator', /Users/dllu/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.48.0/build_generator.rs:127:25
  === Running binding generator binary: "/Users/dllu/tempusthread 'main' panicked at '/Can't join thread: Any', a/Users/dllu/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.48.0/build_generator.rsv:-159s:e28r
  vice/target/debug/build/opencv-11c85100c2c87d4b/out/release/binding-generator" "/usr/local/Cellar/opencv/4.5.0_2/include/opencv4" "/Users/dllu/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.48.0/src_cpp" "/Users/dllu/tempus/av-service/target/debug/build/opencv-11c85100c2c87d4b/out" "xphoto" "4.3.0" "None"
warning: build failed, waiting for other jobs to finish...
error: build failed
(base) ?101 av-service % echo $DYLD_FALLBACK_LIBRARY_PATH
/Library/Developer/CommandLineTools/Toolchains/XcodeDefault.xctoolchain/usr/lib/
```

As you can see from my last `echo` statement the `DYLD_FALLBACK_LIBRARY_PATH` is set correctly.

The crate is included in my `Cargo.toml` as such:

```
opencv = {version = "0.48", features = ["contrib", "clang-runtime"]}
```

Please note that the `"clang-runtime"` is necessary, otherwise compilation fails on macOS and Linux with 

```
  === Generating code in: /Users/dllu/tempus/av-service/target/debug/build/opencv-407633d3753a153b/out
  === Placing generated bindings into: /Users/dllu/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.48.0/bindings/rust/opencv_4
  thread 'main' panicked at 'a `libclang` shared library is not loaded on this thread', /Users/dllu/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-1.0.1/src/lib.rs:1672:1
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by dllu** [comment]
Okay, I figured it out. The documentation is out of date. On Catalina it should be this instead:

```
DYLD_FALLBACK_LIBRARY_PATH="$(xcode-select --print-path)/usr/lib"
```

**Comment by twistedfall** [comment]
There was a [PR](https://github.com/twistedfall/opencv-rust/pull/173) with this change recently, but it was closed due to not being clear whether the issue is actually valid. Do you happen to know why there is a difference between our environments? My macOS knowledge is extremely limited.

**Comment by dllu** [comment]
Hmm, I think one of them is xcode command line tools and the other one is inside the xcode app itself. Xcode bundles its own command line tools but the command line tools may also be installed separately.

This is purely speculation but I suspect that if you install the former first (e.g. via `xcode-select --install` or various other scripts) then `xcode-select --print-path` will be at

```
/Library/Developer/CommandLineTools/
```

and then you'll need to append `/usr/lib`.

But if you install the full xcode first, it will be at

```
/Applications/Xcode.app/Contents/Developer/
```

and then you can append either `/usr/lib` or `Toolchains/XcodeDefault.xctoolchain/usr/lib/` (both should exist, as you pointed out).

After having both installed you can switch between them with `xcode-select -switch` and possibly a drop down menu from the system preferences too. 

In any case, I think the situation where one needs

```
DYLD_FALLBACK_LIBRARY_PATH="$(xcode-select --print-path)/usr/lib"
```

is a lot more common than

```
DYLD_FALLBACK_LIBRARY_PATH="$(xcode-select --print-path)/Toolchains/XcodeDefault.xctoolchain/usr/lib/"
```

as two of my coworkers as well as me needed to set the former environment variable.

Perhaps you can mention both of these on the readme?

**Comment by twistedfall** [comment]
Makes sense, thanks for checking out! I'll update the docs correspondingly.

**Comment by twistedfall** [comment]
Updated in master, thanks!
