### ISSUE TITLE
Build fail on ARM

### ISSUE THREAD

**Issue by laibulle** [twistedfall/opencv-rust#25]
Hi, 

the build on ARM with opencv2.4 and Rust 0.14 produce this error:

```
failed to run custom build command for `opencv v0.2.3`
process didn't exit successfully: `/home/pi/mirror/target/debug/build/opencv-41a4551118b8eb5b/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-search=native=/usr/local/lib
cargo:rustc-link-lib=opencv_shape
cargo:rustc-link-lib=opencv_stitching
cargo:rustc-link-lib=opencv_objdetect
cargo:rustc-link-lib=opencv_superres
cargo:rustc-link-lib=opencv_videostab
cargo:rustc-link-lib=opencv_calib3d
cargo:rustc-link-lib=opencv_features2d
cargo:rustc-link-lib=opencv_highgui
cargo:rustc-link-lib=opencv_videoio
cargo:rustc-link-lib=opencv_imgcodecs
cargo:rustc-link-lib=opencv_video
cargo:rustc-link-lib=opencv_photo
cargo:rustc-link-lib=opencv_ml
cargo:rustc-link-lib=opencv_imgproc
cargo:rustc-link-lib=opencv_flann
cargo:rustc-link-lib=opencv_core
OpenCV lives in "/usr/local/include/opencv2"
Generating code in "/home/pi/mirror/target/debug/build/opencv-41a4551118b8eb5b/out"
Generating module 'core' from headers:
	/usr/local/include/opencv2/core/types_c.h
	/usr/local/include/opencv2/core/core.hpp

--- stderr
Traceback (most recent call last):
  File "gen_rust.py", line 1689, in <module>
    generator.gen(srcfiles, module, dstdir)
  File "gen_rust.py", line 1240, in gen
    self.add_decl(decl)
  File "gen_rust.py", line 1210, in add_decl
    FuncInfo(self, decl, namespaces=self.namespaces)
  File "gen_rust.py", line 476, in __init__
    raise NameError("class not found: " + self.classname)
NameError: class not found: operator cv
thread 'main' panicked at 'explicit panic', /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.2.3/build.rs:86
stack backtrace:
   1: 0x54b7e5e3 - std::sys::imp::backtrace::tracing::imp::write::hc8e8bfe92a700648
                at /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2: 0x54b8555b - std::panicking::default_hook::{{closure}}::h495995576e43d115
                at /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libstd/panicking.rs:247
   3: 0x54b8384f - std::panicking::default_hook::h5063eab0febd8f2b
                at /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libstd/panicking.rs:263
   4: 0x54b83f73 - std::panicking::rust_panic_with_hook::h68a3cd81b9c4603b
                at /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libstd/panicking.rs:451
   5: 0x54b029db - std::panicking::begin_panic::h95f8d5b142fc1dc6
                at /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libstd/panicking.rs:413
   6: 0x54b10ff3 - build_script_build::main::hc93c71ba98cf82a1
                at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.2.3/build.rs:86
   7: 0x54b894ef - __rust_maybe_catch_panic
                at /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libpanic_unwind/lib.rs:97
   8: 0x54b8463f - std::rt::lang_start::h47c287c39e42af0f
                at /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libstd/panicking.rs:332
                at /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libstd/panic.rs:351
                at /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libstd/rt.rs:57
   9: 0x54b134bf - main
  10: 0x76deb293 - __libc_start_main
```

Do you have any idea of what is wrong?

Thanks

**Comment by twistedfall** [comment]
Please check the latest master. I've successfully built the create for usage on raspberry pi. I've tested only against opencv-3.4.5 though, I'm not sure how opencv-2 would fare.
