### ISSUE TITLE
Bindgen OpenCV C++ project and opencv-rust in one project causing panic in build

### ISSUE THREAD

**Issue by JonBoyleCoding** [twistedfall/opencv-rust#276]
I have a C++ library using OpenCV and via an interface project I made, using bindgen to be able to use in Rust - this works without issue. I'm using the rust cmake package to build the interface to this project, and this doesn't itself link to opencv.

When I add this crate to the project, then I start getting the error that I've listed below. To be clear, this crate works fine on it's own in a separate project, but as soon as I combine the two, this crate's build fails with the following panic:

```
thread 'main' panicked at 'a `libclang` shared library is not loaded on this thread', /home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-1.2.2/src/lib.rs:1682:1
```

I have versions of this interface project both using OpenCV and without, and the error is the same. Do you have any thoughts as to what could be going on and if there is a way to fix it? To note, this library I am using is proprietary and do not know how it is compiled.

Thanks for having a look.

The full stack trace is below:
```
error: failed to run custom build command for `opencv v0.54.0`

Caused by:
  process didn't exit successfully: `/home/jonathan/Projects/library-server/library-bindings/target/debug/build/opencv-95060c4331d8392b/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=OPENCV4_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=OPENCV4_STATIC
  cargo:rerun-if-env-changed=OPENCV4_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=SYSROOT
  cargo:rerun-if-env-changed=OPENCV4_STATIC
  cargo:rerun-if-env-changed=OPENCV4_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=OPENCV4_STATIC
  cargo:rerun-if-env-changed=OPENCV4_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:rustc-cfg=ocvrs_opencv_branch_4
  cargo:rerun-if-env-changed=OPENCV_PACKAGE_NAME
  cargo:rerun-if-env-changed=OPENCV_PKGCONFIG_NAME
  cargo:rerun-if-env-changed=OPENCV_CMAKE_NAME
  cargo:rerun-if-env-changed=OPENCV_CMAKE_BIN
  cargo:rerun-if-env-changed=OPENCV_VCPKG_NAME
  cargo:rerun-if-env-changed=OPENCV_LINK_LIBS
  cargo:rerun-if-env-changed=OPENCV_LINK_PATHS
  cargo:rerun-if-env-changed=OPENCV_INCLUDE_PATHS
  cargo:rerun-if-env-changed=OPENCV_DISABLE_PROBES
  cargo:rerun-if-env-changed=OPENCV_MODULE_WHITELIST
  cargo:rerun-if-env-changed=OPENCV_MODULE_BLACKLIST
  cargo:rerun-if-env-changed=CMAKE_PREFIX_PATH
  cargo:rerun-if-env-changed=OpenCV_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=VCPKG_ROOT
  cargo:rerun-if-env-changed=VCPKGRS_DYNAMIC
  cargo:rerun-if-changed=/home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.54.0/src_cpp/videoio.hpp
  cargo:rerun-if-changed=/home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.54.0/src_cpp/core.hpp
  cargo:rerun-if-changed=/home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.54.0/src_cpp/photo.hpp
  cargo:rerun-if-changed=/home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.54.0/src_cpp/xfeatures2d.hpp
  cargo:rerun-if-changed=/home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.54.0/src_cpp/sfm.hpp
  cargo:rerun-if-changed=/home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.54.0/src_cpp/alphamat.hpp
  cargo:rerun-if-changed=/home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.54.0/src_cpp/dnn.hpp
  cargo:rerun-if-changed=/home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.54.0/src_cpp/face.hpp
  cargo:rerun-if-changed=/home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.54.0/src_cpp/ocvrs_common.hpp
  cargo:rerun-if-changed=/home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.54.0/src_cpp/hdf.hpp
  cargo:rerun-if-changed=/home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.54.0/src_cpp/gapi.hpp
  cargo:rerun-if-changed=/home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.54.0/src_cpp/aruco.hpp
  cargo:rerun-if-changed=/home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.54.0/src_cpp/ccalib.hpp
  cargo:rerun-if-changed=/home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.54.0/src_cpp/manual-features2d.cpp
  cargo:rerun-if-changed=/home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.54.0/src_cpp/manual-dnn.cpp
  cargo:rerun-if-changed=/home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.54.0/src_cpp/manual-core.cpp
  cargo:rerun-if-changed=/home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.54.0/src_cpp/bioinspired.hpp

  --- stderr
  === Crate version: Some("0.54.0")
  === Environment configuration:
  ===   OPENCV_PACKAGE_NAME = None
  ===   OPENCV_PKGCONFIG_NAME = None
  ===   OPENCV_CMAKE_NAME = None
  ===   OPENCV_CMAKE_BIN = None
  ===   OPENCV_VCPKG_NAME = None
  ===   OPENCV_LINK_LIBS = None
  ===   OPENCV_LINK_PATHS = None
  ===   OPENCV_INCLUDE_PATHS = None
  ===   OPENCV_DISABLE_PROBES = None
  ===   OPENCV_MODULE_WHITELIST = None
  ===   OPENCV_MODULE_BLACKLIST = None
  ===   CMAKE_PREFIX_PATH = None
  ===   OpenCV_DIR = None
  ===   PKG_CONFIG_PATH = None
  ===   VCPKG_ROOT = None
  ===   VCPKGRS_DYNAMIC = None
  === Enabled features:
  === Detected probe priority based on environment vars: pkg_config: false, cmake: false, vcpkg: false
  === Probing the OpenCV library in the following order: environment, pkg_config, cmake, vcpkg_cmake, vcpkg
  === Can't probe using: environment, continuing with other methods because: Some environment variables are missing
  === Probing OpenCV library using pkg_config
  === OpenCV library configuration: Library {
      include_paths: [
          "/usr/include/opencv4/opencv",
          "/usr/include/opencv4",
      ],
      version: Version {
          major: 4,
          minor: 2,
          patch: 0,
      },
      cargo_metadata: [
          "cargo:rustc-link-search=/usr/lib/x86_64-linux-gnu",
          "cargo:rustc-link-lib=opencv_stitching",
          "cargo:rustc-link-lib=opencv_aruco",
          "cargo:rustc-link-lib=opencv_bgsegm",
          "cargo:rustc-link-lib=opencv_bioinspired",
          "cargo:rustc-link-lib=opencv_ccalib",
          "cargo:rustc-link-lib=opencv_dnn_objdetect",
          "cargo:rustc-link-lib=opencv_dnn_superres",
          "cargo:rustc-link-lib=opencv_dpm",
          "cargo:rustc-link-lib=opencv_highgui",
          "cargo:rustc-link-lib=opencv_face",
          "cargo:rustc-link-lib=opencv_freetype",
          "cargo:rustc-link-lib=opencv_fuzzy",
          "cargo:rustc-link-lib=opencv_hdf",
          "cargo:rustc-link-lib=opencv_hfs",
          "cargo:rustc-link-lib=opencv_img_hash",
          "cargo:rustc-link-lib=opencv_line_descriptor",
          "cargo:rustc-link-lib=opencv_quality",
          "cargo:rustc-link-lib=opencv_reg",
          "cargo:rustc-link-lib=opencv_rgbd",
          "cargo:rustc-link-lib=opencv_saliency",
          "cargo:rustc-link-lib=opencv_shape",
          "cargo:rustc-link-lib=opencv_stereo",
          "cargo:rustc-link-lib=opencv_structured_light",
          "cargo:rustc-link-lib=opencv_phase_unwrapping",
          "cargo:rustc-link-lib=opencv_superres",
          "cargo:rustc-link-lib=opencv_optflow",
          "cargo:rustc-link-lib=opencv_surface_matching",
          "cargo:rustc-link-lib=opencv_tracking",
          "cargo:rustc-link-lib=opencv_datasets",
          "cargo:rustc-link-lib=opencv_text",
          "cargo:rustc-link-lib=opencv_dnn",
          "cargo:rustc-link-lib=opencv_plot",
          "cargo:rustc-link-lib=opencv_ml",
          "cargo:rustc-link-lib=opencv_videostab",
          "cargo:rustc-link-lib=opencv_videoio",
          "cargo:rustc-link-lib=opencv_viz",
          "cargo:rustc-link-lib=opencv_ximgproc",
          "cargo:rustc-link-lib=opencv_video",
          "cargo:rustc-link-lib=opencv_xobjdetect",
          "cargo:rustc-link-lib=opencv_objdetect",
          "cargo:rustc-link-lib=opencv_calib3d",
          "cargo:rustc-link-lib=opencv_imgcodecs",
          "cargo:rustc-link-lib=opencv_features2d",
          "cargo:rustc-link-lib=opencv_flann",
          "cargo:rustc-link-lib=opencv_xphoto",
          "cargo:rustc-link-lib=opencv_photo",
          "cargo:rustc-link-lib=opencv_imgproc",
          "cargo:rustc-link-lib=opencv_core",
      ],
  }
  === Found OpenCV version: 4.2.0 in headers located at: /usr/include/opencv4
  === Generating code in: /home/jonathan/Projects/library-server/library-bindings/target/debug/build/opencv-719cfa377f6c7638/out
  === Placing generated bindings into: /home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.54.0/src/opencv
  === Using OpenCV headers from: /usr/include/opencv4/opencv2
  thread 'main' panicked at 'a `libclang` shared library is not loaded on this thread', /home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-1.2.2/src/lib.rs:1682:1
  stack backtrace:
     0:     0x5631e575ad90 - std::backtrace_rs::backtrace::libunwind::trace::ha0ad43e8a952bfe7
                                 at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
     1:     0x5631e575ad90 - std::backtrace_rs::backtrace::trace_unsynchronized::h6830419c0c4130dc
                                 at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x5631e575ad90 - std::sys_common::backtrace::_print_fmt::h8f3516631ffa1ef5
                                 at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:67:5
     3:     0x5631e575ad90 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he1640d5f0d93f618
                                 at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:46:22
     4:     0x5631e57810ac - core::fmt::write::h88012e1f01caeebf
                                 at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/fmt/mod.rs:1115:17
     5:     0x5631e57572d5 - std::io::Write::write_fmt::h360fa85b30182555
                                 at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/io/mod.rs:1665:15
     6:     0x5631e575d3bb - std::sys_common::backtrace::_print::ha1f00492f406a015
                                 at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:49:5
     7:     0x5631e575d3bb - std::sys_common::backtrace::print::hd54561b13feb6af3
                                 at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:36:9
     8:     0x5631e575d3bb - std::panicking::default_hook::{{closure}}::h84fe124cd0864662
                                 at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:208:50
     9:     0x5631e575ce91 - std::panicking::default_hook::h5a8e74a76ce290a7
                                 at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:225:9
    10:     0x5631e575da84 - std::panicking::rust_panic_with_hook::h67c812a4fe9d4c91
                                 at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:622:17
    11:     0x5631e575d567 - std::panicking::begin_panic_handler::{{closure}}::h33f9c1b96af300d7
                                 at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:519:13
    12:     0x5631e575b28c - std::sys_common::backtrace::__rust_end_short_backtrace::h51bae64be5921f0e
                                 at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:141:18
    13:     0x5631e575d4c9 - rust_begin_unwind
                                 at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
    14:     0x5631e51e1931 - core::panicking::panic_fmt::h12a3a3c256485fca
                                 at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
    15:     0x5631e51e1823 - core::option::expect_failed::h7db74b1e3f5289b2
                                 at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/option.rs:1578:5
    16:     0x5631e56ed1be - core::option::Option<T>::expect::he5c8911f68ec85dd
                                 at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/option.rs:685:21
    17:     0x5631e56d51ec - clang_sys::clang_getClangVersion::h7a0df74f20cdf695
                                 at /home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-1.2.2/src/link.rs:157:25
    18:     0x5631e56a5824 - clang::get_version::h710358d7ae3ad2d0
                                 at /home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-1.0.3/src/lib.rs:3612:33
    19:     0x5631e51f1a02 - build_script_build::generator::gen_wrapper::h231c42cbbf9d81cb
                                 at /home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.54.0/build/generator.rs:85:28
    20:     0x5631e5212fa8 - build_script_build::main::h259da78ba1ac8ab7
                                 at /home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.54.0/build.rs:334:2
    21:     0x5631e51fcaab - core::ops::function::FnOnce::call_once::h98cb3504d096b94f
                                 at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:227:5
    22:     0x5631e5205d2e - std::sys_common::backtrace::__rust_begin_short_backtrace::h02ee62433247214f
                                 at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:125:18
    23:     0x5631e51fbf31 - std::rt::lang_start::{{closure}}::h8bf4dafc595f1f0a
                                 at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/rt.rs:63:18
    24:     0x5631e575df8a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::ha9408abe89f69dc4
                                 at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:259:13
    25:     0x5631e575df8a - std::panicking::try::do_call::h5b0cc9e9102acb65
                                 at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:401:40
    26:     0x5631e575df8a - std::panicking::try::hddc7f8229138b3ba
                                 at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:365:19
    27:     0x5631e575df8a - std::panic::catch_unwind::hfa401ff8bab2986e
                                 at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panic.rs:434:14
    28:     0x5631e575df8a - std::rt::lang_start_internal::{{closure}}::h8163422320d11405
                                 at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/rt.rs:45:48
    29:     0x5631e575df8a - std::panicking::try::do_call::hc742cc7bb4f0fb20
                                 at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:401:40
    30:     0x5631e575df8a - std::panicking::try::ha37d8d2dd1acf7d3
                                 at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:365:19
    31:     0x5631e575df8a - std::panic::catch_unwind::h8a5381d5ecf437bc
                                 at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panic.rs:434:14
    32:     0x5631e575df8a - std::rt::lang_start_internal::h7e2cee8c90d4a4d3
                                 at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/rt.rs:45:20
    33:     0x5631e51fbf00 - std::rt::lang_start::h3cd3d73c560b0a10
                                 at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/rt.rs:62:5
    34:     0x5631e521348c - main
    35:     0x7f82ebef30b3 - __libc_start_main
    36:     0x5631e51e212e - _start
    37:                0x0 - <unknown>

```

**Comment by twistedfall** [comment]
Please check the troubleshooting, item 7: https://github.com/twistedfall/opencv-rust/blob/master/README.md#troubleshooting

**Comment by JonBoyleCoding** [comment]
🤦

Thanks. Sorry for not looking there first!
