### ISSUE TITLE
Can this library really be used on windows?

### ISSUE THREAD

**Issue by nanchengjiumeng** [twistedfall/opencv-rust#395]
No matter how I install llvm or opencv4.
I get this error:
```
  === WARNING: 1 diagnostic messages
  ===    D:\sources\opencv43064\opencv\build\include\opencv2/core/cvdef.h:171:10: fatal error: 'limits' file not found
  thread 'main' panicked at '=== Errors during header parsing', C:\Users\wang7\.cargo\registry\src\github.com-1ecc6299db9ec823\opencv-binding-generator-0.52.0\src\generator.rs:497:17
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  thread '<unnamed>' panicked at 'Failed to run the bindings generator', C:\Users\wang7\.cargo\registry\src\github.com-1ecc6299db9ec823\opencv-0.74.0\build\generator.rs:126:21
  === WARNING: 1 diagnostic messages
  ===    D:\sources\opencv43064\opencv\build\include\opencv2/core/cvdef.h:171:10: fatal error: 'limits' file not found
  thread 'main' panicked at '=== Errors during header parsing', C:\Users\wang7\.cargo\registry\src\github.com-1ecc6299db9ec823\opencv-binding-generator-0.52.0\src\generator.rs:497:17
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  === WARNING: 1 diagnostic messages
  ===    D:\sources\opencv43064\opencv\build\include\opencv2/core/cvdef.h:171:10: fatal error: 'limits' file not found
  thread 'main' panicked at '=== Errors during header parsing', C:\Users\wang7\.cargo\registry\src\github.com-1ecc6299db9ec823\opencv-binding-generator-0.52.0\src\generator.rs:497:17
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  thread '<unnamed>' panicked at 'Failed to run the bindings generator', C:\Users\wang7\.cargo\registry\src\github.com-1ecc6299db9ec823\opencv-0.74.0\build\generator.rs:126:21
  thread '<unnamed>' panicked at 'Failed to run the bindings generator', C:\Users\wang7\.cargo\registry\src\github.com-1ecc6299db9ec823\opencv-0.74.0\build\generator.rs:126:21
  thread '<unnamed>' panicked at 'Failed to run the bindings generator', C:\Users\wang7\.cargo\registry\src\github.com-1ecc6299db9ec823\opencv-0.74.0\build\generator.rs:126:21
  thread 'main' panicked at 'Generator thread panicked: Any { .. }', C:\Users\wang7\.cargo\registry\src\github.com-1ecc6299db9ec823\opencv-0.74.0\build\generator.rs:135:28
  === WARNING: 1 diagnostic messages
  ===    D:\sources\opencv43064\opencv\build\include\opencv2/core/cvdef.h:171:10: fatal error: 'limits' file not found
  thread 'main' panicked at '=== Errors during header parsing', C:\Users\wang7\.cargo\registry\src\github.com-1ecc6299db9ec823\opencv-binding-generator-0.52.0\src\generator.rs:497:17
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  === WARNING: 1 diagnostic messages
  ===    D:\sources\opencv43064\opencv\build\include\opencv2/core/cvdef.h:171:10: fatal error: 'limits' file not found
  thread 'main' panicked at '=== Errors during header parsing', C:\Users\wang7\.cargo\registry\src\github.com-1ecc6299db9ec823\opencv-binding-generator-0.52.0\src\generator.rs:497:17
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  === WARNING: 1 diagnostic messages
  ===    D:\sources\opencv43064\opencv\build\include\opencv2/core/cvdef.h:171:10: fatal error: 'limits' file not found
  thread 'main' panicked at '=== Errors during header parsing', C:\Users\wang7\.cargo\registry\src\github.com-1ecc6299db9ec823\opencv-binding-generator-0.52.0\src\generator.rs:497:17
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  === WARNING: 1 diagnostic messages
  ===    D:\sources\opencv43064\opencv\build\include\opencv2/core/cvdef.h:171:10: fatal error: 'limits' file not found
  thread 'main' panicked at '=== Errors during header parsing', C:\Users\wang7\.cargo\registry\src\github.com-1ecc6299db9ec823\opencv-binding-generator-0.52.0\src\generator.rs:497:17
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  === WARNING: 1 diagnostic messages
  ===    D:\sources\opencv43064\opencv\build\include\opencv2/core/cvdef.h:171:10: fatal error: 'limits' file not found
  thread 'main' panicked at '=== Errors during header parsing', C:\Users\wang7\.cargo\registry\src\github.com-1ecc6299db9ec823\opencv-binding-generator-0.52.0\src\generator.rs:497:17
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  === WARNING: 1 diagnostic messages
  ===    D:\sources\opencv43064\opencv\build\include\opencv2/core/cvdef.h:171:10: fatal error: 'limits' file not found
  thread 'main' panicked at '=== Errors during header parsing', C:\Users\wang7\.cargo\registry\src\github.com-1ecc6299db9ec823\opencv-binding-generator-0.52.0\src\generator.rs:497:17
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  === WARNING: 1 diagnostic messages
  ===    D:\sources\opencv43064\opencv\build\include\opencv2/core/cvdef.h:171:10: fatal error: 'limits' file not found
  thread 'main' panicked at '=== Errors during header parsing', C:\Users\wang7\.cargo\registry\src\github.com-1ecc6299db9ec823\opencv-binding-generator-0.52.0\src\generator.rs:497:17
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  === WARNING: 1 diagnostic messages
  ===    D:\sources\opencv43064\opencv\build\include\opencv2/core/cvdef.h:171:10: fatal error: 'limits' file not found
  thread 'main' panicked at '=== Errors during header parsing', C:\Users\wang7\.cargo\registry\src\github.com-1ecc6299db9ec823\opencv-binding-generator-0.52.0\src\generator.rs:497:17
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by twistedfall** [comment]
It's a known issue on some Windows machines, I can't reproduce it locally unfortunately. You can find some workarounds in the following bugreport: https://github.com/twistedfall/opencv-rust/issues/322
