### ISSUE TITLE
Build failed on windows in nightly toolchain

### ISSUE THREAD

**Issue by Anivie** [twistedfall/opencv-rust#550]
1. Operating system
Windows11 X64
3. The way you installed OpenCV: package, official binary distribution, manual compilation, etc.
manual compilation
4. OpenCV version
4.9.0
6. rustc version (`rustc --version`)
rustc 1.78.0-nightly (4a0cc881d 2024-03-11)
8. Attach the full output of the following command from your project directory:
```shell script
  === Detected probe priority based on environment vars: pkg_config: false, cmake: true, vcpkg: false
  === Probing the OpenCV library in the following order: environment, cmake, pkg_config, vcpkg_cmake, vcpkg
  === Configuring OpenCV library from the environment:
  ===   include_paths: D:\DevTools\OpenCV\build\include
  ===   link_paths: D:\DevTools\OpenCV\build\x64\vc16\lib
  ===   link_libs: opencv_world490
  === Successfully probed using: environment
  === OpenCV library configuration: Library {
      include_paths: [
          "D:\\DevTools\\OpenCV\\build\\include",
      ],
      version: Version {
          major: 4,
          minor: 9,
          patch: 0,
      },
      cargo_metadata: [
          "cargo:rustc-link-search=D:\\DevTools\\OpenCV\\build\\x64\\vc16\\lib",
          "cargo:rustc-link-lib=opencv_world490",
      ],
  }
  === Detected OpenCV module header dir at: D:\DevTools\OpenCV\build\include\opencv2
  === Found OpenCV version: 4.9.0 in headers located at: D:\DevTools\OpenCV\build\include
  === Generating code in: D:\IDE_WorkSpace\RustRover_WorkSpace\torch-test-win\target\debug\build\opencv-a2081aea51a0a103\out
  === Placing generated bindings into: D:\IDE_WorkSpace\RustRover_WorkSpace\torch-test-win\target\debug\build\opencv-a2081aea51a0a103\out\opencv
  === Using OpenCV headers from: D:\DevTools\OpenCV\build\include
  === Clang: clang version 17.0.1
  === Clang command line args: [
      "-isystemC:\\Program Files\\LLVM\\lib\\clang\\17\\include",
      "-isystemC:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\include",
      "-isystemC:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\atlmfc\\include",
      "-isystemD:\\Windows Kits\\10\\Include\\10.0.22621.0\\ucrt",
      "-isystemD:\\Windows Kits\\10\\Include\\10.0.22621.0\\shared",
      "-isystemD:\\Windows Kits\\10\\Include\\10.0.22621.0\\um",
      "-isystemD:\\Windows Kits\\10\\Include\\10.0.22621.0\\winrt",
      "-isystemD:\\Windows Kits\\10\\Include\\10.0.22621.0\\cppwinrt",
      "-ID:\\DevTools\\OpenCV\\build\\include",
      "-FD:\\DevTools\\OpenCV\\build\\include",
      "-ID:\\SDK\\Rust\\Cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\opencv-0.88.8\\src_cpp",
      "-FD:\\SDK\\Rust\\Cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\opencv-0.88.8\\src_cpp",
      "-DOCVRS_PARSING_HEADERS",
      "-includeocvrs_common.hpp",
      "-std=c++14",
  ]
  === Using environment job server with the the amount of available jobs: 12
  === Generating 15 modules
  === Running: "D:\\IDE_WorkSpace\\RustRover_WorkSpace\\torch-test-win\\target\\debug\\build\\opencv-a4656cef47d16b1f\\build-script-build.exe" "D:\\DevTools\\OpenCV\\build\\include" "D:\\SDK\\Rust\\Cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\opencv-0.88.8\\src_cpp" "D:\\IDE_WorkSpace\\RustRover_WorkSpace\\torch-test-win\\target\\debug\\build\\opencv-a2081aea51a0a103\\out" "calib3d" ""
  === Running: "D:\\IDE_WorkSpace\\RustRover_WorkSpace\\torch-test-win\\target\\debug\\build\\opencv-a4656cef47d16b1f\\build-script-build.exe" "D:\\DevTools\\OpenCV\\build\\include" "D:\\SDK\\Rust\\Cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\opencv-0.88.8\\src_cpp" "D:\\IDE_WorkSpace\\RustRover_WorkSpace\\torch-test-win\\target\\debug\\build\\opencv-a2081aea51a0a103\\out" "flann" ""
  === Running: "D:\\IDE_WorkSpace\\RustRover_WorkSpace\\torch-test-win\\target\\debug\\build\\opencv-a4656cef47d16b1f\\build-script-build.exe" "D:\\DevTools\\OpenCV\\build\\include" "D:\\SDK\\Rust\\Cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\opencv-0.88.8\\src_cpp" "D:\\IDE_WorkSpace\\RustRover_WorkSpace\\torch-test-win\\target\\debug\\build\\opencv-a2081aea51a0a103\\out" "imgcodecs" ""
  === Running: "D:\\IDE_WorkSpace\\RustRover_WorkSpace\\torch-test-win\\target\\debug\\build\\opencv-a4656cef47d16b1f\\build-script-build.exe" "D:\\DevTools\\OpenCV\\build\\include" "D:\\SDK\\Rust\\Cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\opencv-0.88.8\\src_cpp" "D:\\IDE_WorkSpace\\RustRover_WorkSpace\\torch-test-win\\target\\debug\\build\\opencv-a2081aea51a0a103\\out" "ml" ""
  === Running: "D:\\IDE_WorkSpace\\RustRover_WorkSpace\\torch-test-win\\target\\debug\\build\\opencv-a4656cef47d16b1f\\build-script-build.exe" "D:\\DevTools\\OpenCV\\build\\include" "D:\\SDK\\Rust\\Cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\opencv-0.88.8\\src_cpp" "D:\\IDE_WorkSpace\\RustRover_WorkSpace\\torch-test-win\\target\\debug\\build\\opencv-a2081aea51a0a103\\out" "core" ""
  === Running: "D:\\IDE_WorkSpace\\RustRover_WorkSpace\\torch-test-win\\target\\debug\\build\\opencv-a4656cef47d16b1f\\build-script-build.exe" "D:\\DevTools\\OpenCV\\build\\include" "D:\\SDK\\Rust\\Cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\opencv-0.88.8\\src_cpp" "D:\\IDE_WorkSpace\\RustRover_WorkSpace\\torch-test-win\\target\\debug\\build\\opencv-a2081aea51a0a103\\out" "gapi" ""
  === Running: "D:\\IDE_WorkSpace\\RustRover_WorkSpace\\torch-test-win\\target\\debug\\build\\opencv-a4656cef47d16b1f\\build-script-build.exe" "D:\\DevTools\\OpenCV\\build\\include" "D:\\SDK\\Rust\\Cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\opencv-0.88.8\\src_cpp" "D:\\IDE_WorkSpace\\RustRover_WorkSpace\\torch-test-win\\target\\debug\\build\\opencv-a2081aea51a0a103\\out" "highgui" ""
  === Running: "D:\\IDE_WorkSpace\\RustRover_WorkSpace\\torch-test-win\\target\\debug\\build\\opencv-a4656cef47d16b1f\\build-script-build.exe" "D:\\DevTools\\OpenCV\\build\\include" "D:\\SDK\\Rust\\Cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\opencv-0.88.8\\src_cpp" "D:\\IDE_WorkSpace\\RustRover_WorkSpace\\torch-test-win\\target\\debug\\build\\opencv-a2081aea51a0a103\\out" "dnn" ""
  === Running: "D:\\IDE_WorkSpace\\RustRover_WorkSpace\\torch-test-win\\target\\debug\\build\\opencv-a4656cef47d16b1f\\build-script-build.exe" "D:\\DevTools\\OpenCV\\build\\include" "D:\\SDK\\Rust\\Cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\opencv-0.88.8\\src_cpp" "D:\\IDE_WorkSpace\\RustRover_WorkSpace\\torch-test-win\\target\\debug\\build\\opencv-a2081aea51a0a103\\out" "imgproc" ""
  === Running: "D:\\IDE_WorkSpace\\RustRover_WorkSpace\\torch-test-win\\target\\debug\\build\\opencv-a4656cef47d16b1f\\build-script-build.exe" "D:\\DevTools\\OpenCV\\build\\include" "D:\\SDK\\Rust\\Cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\opencv-0.88.8\\src_cpp" "D:\\IDE_WorkSpace\\RustRover_WorkSpace\\torch-test-win\\target\\debug\\build\\opencv-a2081aea51a0a103\\out" "features2d" ""
  === Running: "D:\\IDE_WorkSpace\\RustRover_WorkSpace\\torch-test-win\\target\\debug\\build\\opencv-a4656cef47d16b1f\\build-script-build.exe" "D:\\DevTools\\OpenCV\\build\\include" "D:\\SDK\\Rust\\Cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\opencv-0.88.8\\src_cpp" "D:\\IDE_WorkSpace\\RustRover_WorkSpace\\torch-test-win\\target\\debug\\build\\opencv-a2081aea51a0a103\\out" "objdetect" ""
  === Running: "D:\\IDE_WorkSpace\\RustRover_WorkSpace\\torch-test-win\\target\\debug\\build\\opencv-a4656cef47d16b1f\\build-script-build.exe" "D:\\DevTools\\OpenCV\\build\\include" "D:\\SDK\\Rust\\Cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\opencv-0.88.8\\src_cpp" "D:\\IDE_WorkSpace\\RustRover_WorkSpace\\torch-test-win\\target\\debug\\build\\opencv-a2081aea51a0a103\\out" "photo" ""
  === Generated: imgcodecs in 1.7422751s
  === Generated: highgui in 1.7421074s
  === Running: "D:\\IDE_WorkSpace\\RustRover_WorkSpace\\torch-test-win\\target\\debug\\build\\opencv-a4656cef47d16b1f\\build-script-build.exe" "D:\\DevTools\\OpenCV\\build\\include" "D:\\SDK\\Rust\\Cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\opencv-0.88.8\\src_cpp" "D:\\IDE_WorkSpace\\RustRover_WorkSpace\\torch-test-win\\target\\debug\\build\\opencv-a2081aea51a0a103\\out" "stitching" ""
  === Running: "D:\\IDE_WorkSpace\\RustRover_WorkSpace\\torch-test-win\\target\\debug\\build\\opencv-a4656cef47d16b1f\\build-script-build.exe" "D:\\DevTools\\OpenCV\\build\\include" "D:\\SDK\\Rust\\Cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\opencv-0.88.8\\src_cpp" "D:\\IDE_WorkSpace\\RustRover_WorkSpace\\torch-test-win\\target\\debug\\build\\opencv-a2081aea51a0a103\\out" "video" ""
  === Generated: flann in 1.8760629s
  === Running: "D:\\IDE_WorkSpace\\RustRover_WorkSpace\\torch-test-win\\target\\debug\\build\\opencv-a4656cef47d16b1f\\build-script-build.exe" "D:\\DevTools\\OpenCV\\build\\include" "D:\\SDK\\Rust\\Cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\opencv-0.88.8\\src_cpp" "D:\\IDE_WorkSpace\\RustRover_WorkSpace\\torch-test-win\\target\\debug\\build\\opencv-a2081aea51a0a103\\out" "videoio" ""
  thread 'main' panicked at library\core\src\panicking.rs:156:5:
  unsafe precondition(s) violated: slice::from_raw_parts requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  thread caused non-unwinding panic. aborting.
  thread '<unnamed>' panicked at D:\SDK\Rust\Cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-0.88.8\build\generator.rs:110:33:
  Failed to run the bindings generator for module: dnn
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  === Generated: photo in 2.7076265s
  === Generated: ml in 3.0319526s
  === Generated: features2d in 3.3650016s
  === Generated: videoio in 1.7822881s
  === Generated: objdetect in 3.658286s
  === Generated: video in 2.2049711s
  === Generated: gapi in 4.0775791s
  === Generated: imgproc in 4.1356025s
  === Generated: calib3d in 4.1957573s
  === Generated: stitching in 3.7352342s
  === Generated: core in 7.2803317s
  thread 'main' panicked at D:\SDK\Rust\Cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-0.88.8\build\generator.rs:119:36:
  Generator process panicked: Any { .. }
warning: build failed, waiting for other jobs to finish...
```

**Comment by twistedfall** [comment]
Judging by the error message it's related to https://github.com/twistedfall/opencv-rust/issues/548, I'm going to close this issue in favor or that one
