### ISSUE TITLE
Can't use opencv in Windows: C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-0.92.0\src_cpp\ocvrs_common.hpp:16:10: fatal error: 'memory' file not found

### ISSUE THREAD

**Issue by manuelarte** [twistedfall/opencv-rust#594]
I followed the instructions described in INSTALLATION.md but I am getting the following error:

  ===    C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-0.92.0\src_cpp\ocvrs_common.hpp:16:10: fatal error: 'memory' file not found
  thread 'main' panicked at C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-binding-generator-0.90.0\src\generator.rs:402:17:
  === Errors during header parsing
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:652
     1: core::panicking::panic_fmt
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\panicking.rs:72
     2: opencv_binding_generator::generator::Generator::handle_diags
     3: opencv_binding_generator::generator::OpenCvWalker<V>::process_typedef::{{closure}}
     4: opencv_binding_generator::generator::Generator::generate
     5: build_script_build::binding_generator::handle_running_binding_generator
     6: build_script_build::binding_generator::handle_running_binding_generator
     7: build_script_build::setup_rerun::{{closure}}::{{closure}}
     8: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  === WARNING: 1 diagnostic messages
  ===    C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-0.92.0\src_cpp\ocvrs_common.hpp:16:10: fatal error: 'memory' file not found
  thread 'main' panicked at C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-binding-generator-0.90.0\src\generator.rs:402:17:
  === Errors during header parsing
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:652
     1: core::panicking::panic_fmt
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\panicking.rs:72
     2: opencv_binding_generator::generator::Generator::handle_diags
     3: opencv_binding_generator::generator::OpenCvWalker<V>::process_typedef::{{closure}}
     4: opencv_binding_generator::generator::Generator::generate
     5: build_script_build::binding_generator::handle_running_binding_generator
     6: build_script_build::binding_generator::handle_running_binding_generator
     7: build_script_build::setup_rerun::{{closure}}::{{closure}}
     8: core::ops::function::FnOnce::call_once
  thread '<unnamed>' panicked at C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-0.92.0\build\generator.rs:109:33:
  Failed to run the bindings generator for module: calib3d
  stack backtrace:
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
     0: std::panicking::begin_panic_handler
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:652
     1: core::panicking::panic_fmt
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\panicking.rs:72
     2: build_script_build::generator::BindingGenerator::run::{{closure}}::{{closure}}::{{closure}}
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  thread 'main' panicked at C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-0.92.0\build\generator.rs:118:36:
  Generator process panicked: Any { .. }
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:652
     1: core::panicking::panic_fmt
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\panicking.rs:72
     2: core::result::unwrap_failed
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\result.rs:1654
     3: core::result::Result<T,E>::expect
     4: build_script_build::generator::BindingGenerator::run::{{closure}}
     5: std::thread::scoped::scope::{{closure}}
     6: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
     7: std::panicking::try
     8: build_script_build::docs::transfer_bindings_to_docs::{{closure}}
     9: std::panicking::try
    10: std::thread::scoped::scope
    11: build_script_build::generator::BindingGenerator::generate_wrapper::{{closure}}::{{closure}}
    12: build_script_build::generator::BindingGenerator::generate_wrapper
    13: build_script_build::setup_rerun::{{closure}}::{{closure}}
    14: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  thread '<unnamed>' panicked at C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-0.92.0\build\generator.rs:109:33:
  Failed to run the bindings generator for module: dnn
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:652
     1: core::panicking::panic_fmt
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\panicking.rs:72
     2: build_script_build::generator::BindingGenerator::run::{{closure}}::{{closure}}::{{closure}}
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  === WARNING: 1 diagnostic messages
  ===    C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-0.92.0\src_cpp\ocvrs_common.hpp:16:10: fatal error: 'memory' file not found
  thread 'main' panicked at C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-binding-generator-0.90.0\src\generator.rs:402:17:
  === Errors during header parsing
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:652
     1: core::panicking::panic_fmt
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\panicking.rs:72
     2: opencv_binding_generator::generator::Generator::handle_diags
     3: opencv_binding_generator::generator::OpenCvWalker<V>::process_typedef::{{closure}}
     4: opencv_binding_generator::generator::Generator::generate
     5: build_script_build::binding_generator::handle_running_binding_generator
     6: build_script_build::binding_generator::handle_running_binding_generator
     7: build_script_build::setup_rerun::{{closure}}::{{closure}}
     8: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  === WARNING: 1 diagnostic messages
  ===    C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-0.92.0\src_cpp\ocvrs_common.hpp:16:10: fatal error: 'memory' file not found
  thread 'main' panicked at C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-binding-generator-0.90.0\src\generator.rs:402:17:
  === Errors during header parsing
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:652
     1: core::panicking::panic_fmt
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\panicking.rs:72
     2: opencv_binding_generator::generator::Generator::handle_diags
     3: opencv_binding_generator::generator::OpenCvWalker<V>::process_typedef::{{closure}}
     4: opencv_binding_generator::generator::Generator::generate
     5: build_script_build::binding_generator::handle_running_binding_generator
     6: build_script_build::binding_generator::handle_running_binding_generator
     7: build_script_build::setup_rerun::{{closure}}::{{closure}}
     8: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  === WARNING: 1 diagnostic messages
  ===    C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-0.92.0\src_cpp\ocvrs_common.hpp:16:10: fatal error: 'memory' file not found
  thread 'main' panicked at C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-binding-generator-0.90.0\src\generator.rs:402:17:
  === Errors during header parsing
  stack backtrace:
  thread '<unnamed>' panicked at C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-0.92.0\build\generator.rs:109:33:
  Failed to run the bindings generator for module: features2d
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:652
     1: core::panicking::panic_fmt
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\panicking.rs:72
     2: build_script_build::generator::BindingGenerator::run::{{closure}}::{{closure}}::{{closure}}
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
     0: std::panicking::begin_panic_handler
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:652
     1: core::panicking::panic_fmt
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\panicking.rs:72
     2: opencv_binding_generator::generator::Generator::handle_diags
     3: opencv_binding_generator::generator::OpenCvWalker<V>::process_typedef::{{closure}}
     4: opencv_binding_generator::generator::Generator::generate
     5: build_script_build::binding_generator::handle_running_binding_generator
     6: build_script_build::binding_generator::handle_running_binding_generator
     7: build_script_build::setup_rerun::{{closure}}::{{closure}}
     8: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  thread '<unnamed>' panicked at C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-0.92.0\build\generator.rs:109:33:
  Failed to run the bindings generator for module: flann
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:652
     1: core::panicking::panic_fmt
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\panicking.rs:72
     2: build_script_build::generator::BindingGenerator::run::{{closure}}::{{closure}}::{{closure}}
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  thread '<unnamed>' panicked at C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-0.92.0\build\generator.rs:109:33:
  Failed to run the bindings generator for module: core
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:652
     1: core::panicking::panic_fmt
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\panicking.rs:72
     2: build_script_build::generator::BindingGenerator::run::{{closure}}::{{closure}}::{{closure}}
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  === WARNING: 1 diagnostic messages
  ===    C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-0.92.0\src_cpp\ocvrs_common.hpp:16:10: fatal error: 'memory' file not found
  thread 'main' panicked at C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-binding-generator-0.90.0\src\generator.rs:402:17:
  === Errors during header parsing
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:652
     1: core::panicking::panic_fmt
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\panicking.rs:72
     2: opencv_binding_generator::generator::Generator::handle_diags
     3: opencv_binding_generator::generator::OpenCvWalker<V>::process_typedef::{{closure}}
     4: opencv_binding_generator::generator::Generator::generate
     5: build_script_build::binding_generator::handle_running_binding_generator
     6: build_script_build::binding_generator::handle_running_binding_generator
     7: build_script_build::setup_rerun::{{closure}}::{{closure}}
     8: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  === WARNING: 1 diagnostic messages
  ===    C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-0.92.0\src_cpp\ocvrs_common.hpp:16:10: fatal error: 'memory' file not found
  thread 'main' panicked at C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-binding-generator-0.90.0\src\generator.rs:402:17:
  === Errors during header parsing
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:652
     1: core::panicking::panic_fmt
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\panicking.rs:72
     2: opencv_binding_generator::generator::Generator::handle_diags
     3: opencv_binding_generator::generator::OpenCvWalker<V>::process_typedef::{{closure}}
     4: opencv_binding_generator::generator::Generator::generate
     5: build_script_build::binding_generator::handle_running_binding_generator
     6: build_script_build::binding_generator::handle_running_binding_generator
     7: build_script_build::setup_rerun::{{closure}}::{{closure}}
     8: core::ops::function::FnOnce::call_once
  thread '<unnamed>' panicked at C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-0.92.0\build\generator.rs:109:33:
  Failed to run the bindings generator for module: gapi
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:652
     1: core::panicking::panic_fmt
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\panicking.rs:72
     2: build_script_build::generator::BindingGenerator::run::{{closure}}::{{closure}}::{{closure}}
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  === WARNING: 1 diagnostic messages
  ===    C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-0.92.0\src_cpp\ocvrs_common.hpp:16:10: fatal error: 'memory' file not found
  thread 'main' panicked at C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-binding-generator-0.90.0\src\generator.rs:402:17:
  === Errors during header parsing
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:652
     1: core::panicking::panic_fmt
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\panicking.rs:72
     2: opencv_binding_generator::generator::Generator::handle_diags
     3: opencv_binding_generator::generator::OpenCvWalker<V>::process_typedef::{{closure}}
     4: opencv_binding_generator::generator::Generator::generate
     5: build_script_build::binding_generator::handle_running_binding_generator
     6: build_script_build::binding_generator::handle_running_binding_generator
     7: build_script_build::setup_rerun::{{closure}}::{{closure}}
     8: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  thread '<unnamed>' panicked at C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-0.92.0\build\generator.rs:109:33:
  Failed to run the bindings generator for module: stitching
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:652
     1: core::panicking::panic_fmt
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\panicking.rs:72
     2: build_script_build::generator::BindingGenerator::run::{{closure}}::{{closure}}::{{closure}}
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  === WARNING: 1 diagnostic messages
  ===    C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-0.92.0\src_cpp\ocvrs_common.hpp:16:10: fatal error: 'memory' file not found
  thread 'main' panicked at C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-binding-generator-0.90.0\src\generator.rs:402:17:
  === Errors during header parsing
  stack backtrace:
  thread '<unnamed>' panicked at C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-0.92.0\build\generator.rs:109:33:
  Failed to run the bindings generator for module: imgcodecs
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:652
     1: core::panicking::panic_fmt
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\panicking.rs:72
     2: build_script_build::generator::BindingGenerator::run::{{closure}}::{{closure}}::{{closure}}
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
     0: std::panicking::begin_panic_handler
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:652
     1: core::panicking::panic_fmt
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\panicking.rs:72
     2: opencv_binding_generator::generator::Generator::handle_diags
     3: opencv_binding_generator::generator::OpenCvWalker<V>::process_typedef::{{closure}}
     4: opencv_binding_generator::generator::Generator::generate
     5: build_script_build::binding_generator::handle_running_binding_generator
     6: build_script_build::binding_generator::handle_running_binding_generator
     7: build_script_build::setup_rerun::{{closure}}::{{closure}}
     8: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  === WARNING: 1 diagnostic messages
  ===    C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-0.92.0\src_cpp\ocvrs_common.hpp:16:10: fatal error: 'memory' file not found
  thread 'main' panicked at C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-binding-generator-0.90.0\src\generator.rs:402:17:
  === Errors during header parsing
  stack backtrace:
  thread '<unnamed>' panicked at C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-0.92.0\build\generator.rs:109:33:
  Failed to run the bindings generator for module: imgproc
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:652
     1: core::panicking::panic_fmt
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\panicking.rs:72
     2: build_script_build::generator::BindingGenerator::run::{{closure}}::{{closure}}::{{closure}}
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
     0: std::panicking::begin_panic_handler
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:652
     1: core::panicking::panic_fmt
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\panicking.rs:72
     2: opencv_binding_generator::generator::Generator::handle_diags
     3: opencv_binding_generator::generator::OpenCvWalker<V>::process_typedef::{{closure}}
     4: opencv_binding_generator::generator::Generator::generate
     5: build_script_build::binding_generator::handle_running_binding_generator
     6: build_script_build::binding_generator::handle_running_binding_generator
     7: build_script_build::setup_rerun::{{closure}}::{{closure}}
     8: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  === WARNING: 1 diagnostic messages
  ===    C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-0.92.0\src_cpp\ocvrs_common.hpp:16:10: fatal error: 'memory' file not found
  thread 'main' panicked at C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-binding-generator-0.90.0\src\generator.rs:402:17:
  === Errors during header parsing
  stack backtrace:
  thread '<unnamed>' panicked at C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-0.92.0\build\generator.rs:109:33:
  Failed to run the bindings generator for module: ml
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:652
     1: core::panicking::panic_fmt
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\panicking.rs:72
     2: build_script_build::generator::BindingGenerator::run::{{closure}}::{{closure}}::{{closure}}
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
     0: std::panicking::begin_panic_handler
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:652
     1: core::panicking::panic_fmt
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\panicking.rs:72
     2: opencv_binding_generator::generator::Generator::handle_diags
     3: opencv_binding_generator::generator::OpenCvWalker<V>::process_typedef::{{closure}}
     4: opencv_binding_generator::generator::Generator::generate
     5: build_script_build::binding_generator::handle_running_binding_generator
     6: build_script_build::binding_generator::handle_running_binding_generator
     7: build_script_build::setup_rerun::{{closure}}::{{closure}}
     8: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  thread '<unnamed>' panicked at C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-0.92.0\build\generator.rs:109:33:
  Failed to run the bindings generator for module: objdetect
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:652
     1: core::panicking::panic_fmt
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\panicking.rs:72
     2: build_script_build::generator::BindingGenerator::run::{{closure}}::{{closure}}::{{closure}}
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  === WARNING: 1 diagnostic messages
  ===    C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-0.92.0\src_cpp\ocvrs_common.hpp:16:10: fatal error: 'memory' file not found
  thread 'main' panicked at C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-binding-generator-0.90.0\src\generator.rs:402:17:
  === Errors during header parsing
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:652
     1: core::panicking::panic_fmt
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\panicking.rs:72
     2: opencv_binding_generator::generator::Generator::handle_diags
     3: opencv_binding_generator::generator::OpenCvWalker<V>::process_typedef::{{closure}}
     4: opencv_binding_generator::generator::Generator::generate
     5: build_script_build::binding_generator::handle_running_binding_generator
     6: build_script_build::binding_generator::handle_running_binding_generator
     7: build_script_build::setup_rerun::{{closure}}::{{closure}}
     8: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  === WARNING: 1 diagnostic messages
  ===    C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-0.92.0\src_cpp\ocvrs_common.hpp:16:10: fatal error: 'memory' file not found
  thread 'main' panicked at C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-binding-generator-0.90.0\src\generator.rs:402:17:
  === Errors during header parsing
  stack backtrace:
  thread '<unnamed>' panicked at C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-0.92.0\build\generator.rs:109:33:
  Failed to run the bindings generator for module: photo
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:652
     1: core::panicking::panic_fmt
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\panicking.rs:72
     2: build_script_build::generator::BindingGenerator::run::{{closure}}::{{closure}}::{{closure}}
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
     0: std::panicking::begin_panic_handler
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:652
     1: core::panicking::panic_fmt
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\panicking.rs:72
     2: opencv_binding_generator::generator::Generator::handle_diags
     3: opencv_binding_generator::generator::OpenCvWalker<V>::process_typedef::{{closure}}
     4: opencv_binding_generator::generator::Generator::generate
     5: build_script_build::binding_generator::handle_running_binding_generator
     6: build_script_build::binding_generator::handle_running_binding_generator
     7: build_script_build::setup_rerun::{{closure}}::{{closure}}
     8: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  === WARNING: 1 diagnostic messages
  ===    C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-0.92.0\src_cpp\ocvrs_common.hpp:16:10: fatal error: 'memory' file not found
  thread 'main' panicked at C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-binding-generator-0.90.0\src\generator.rs:402:17:
  === Errors during header parsing
  stack backtrace:
  thread '<unnamed>' panicked at C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-0.92.0\build\generator.rs:109:33:
  Failed to run the bindings generator for module: highgui
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:652
     1: core::panicking::panic_fmt
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\panicking.rs:72
     2: build_script_build::generator::BindingGenerator::run::{{closure}}::{{closure}}::{{closure}}
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
     0: std::panicking::begin_panic_handler
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:652
     1: core::panicking::panic_fmt
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\panicking.rs:72
     2: opencv_binding_generator::generator::Generator::handle_diags
     3: opencv_binding_generator::generator::OpenCvWalker<V>::process_typedef::{{closure}}
     4: opencv_binding_generator::generator::Generator::generate
     5: build_script_build::binding_generator::handle_running_binding_generator
     6: build_script_build::binding_generator::handle_running_binding_generator
     7: build_script_build::setup_rerun::{{closure}}::{{closure}}
     8: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  === WARNING: 1 diagnostic messages
  ===    C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-0.92.0\src_cpp\ocvrs_common.hpp:16:10: fatal error: 'memory' file not found
  thread 'main' panicked at C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-binding-generator-0.90.0\src\generator.rs:402:17:
  === Errors during header parsing
  stack backtrace:
  thread '<unnamed>' panicked at C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-0.92.0\build\generator.rs:109:33:
  Failed to run the bindings generator for module: video
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:652
     1: core::panicking::panic_fmt
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\panicking.rs:72
     2: build_script_build::generator::BindingGenerator::run::{{closure}}::{{closure}}::{{closure}}
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
     0: std::panicking::begin_panic_handler
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:652
     1: core::panicking::panic_fmt
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\panicking.rs:72
     2: opencv_binding_generator::generator::Generator::handle_diags
     3: opencv_binding_generator::generator::OpenCvWalker<V>::process_typedef::{{closure}}
     4: opencv_binding_generator::generator::Generator::generate
     5: build_script_build::binding_generator::handle_running_binding_generator
     6: build_script_build::binding_generator::handle_running_binding_generator
     7: build_script_build::setup_rerun::{{closure}}::{{closure}}
     8: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  thread '<unnamed>' panicked at C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\opencv-0.92.0\build\generator.rs:109:33:
  Failed to run the bindings generator for module: videoio
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:652
     1: core::panicking::panic_fmt
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\panicking.rs:72
     2: build_script_build::generator::BindingGenerator::run::{{closure}}::{{closure}}::{{closure}}
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by limitcool** [comment]
I encountered the same problem

**Comment by alexisgaziello** [comment]
Had the same issue when compiling in a docker image. Resolved it by  setting

ENV LD_LIBRARY_PATH="/usr/lib/llvm-11/lib:"
ENV LIBCLANG_PATH="/usr/lib/llvm-11/lib"

**Comment by twistedfall** [comment]
@alexisgaziello Can you please share the Dockerfile that was causing the issue?

**Comment by lijingrs** [comment]
I encountered the same problem

Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy

gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04) 

use the installl.sh  Unable to compile successfully my opencv-rust project

**Comment by RasmusHogslatt** [comment]
I got the same issue on PopOS 22.04

**Comment by RasmusHogslatt** [comment]
I found a solution, at least for me. The missing memory was due to "CPLUS_INCLUDE_PATH" not being set. Adding this gave me the a new error telling me that some other headers were missing related to C++20 features. I realized my default llvm installation did not give me C++20 clang. The following worked for me:
* Install the pacakges mentioned in install.md: apt install libopencv-dev clang libclang-dev
* Also install libc++-dev and libstdc++-12-abd-dev. Note that the 12 is there to match the GCC 12 version I had. If it does not work, verify that you have a c++config.h where GCC 12 is installed.

**Comment by zhao85** [comment]
> I encountered the same problem
> 
> Distributor ID: Ubuntu Description: Ubuntu 22.04.4 LTS Release: 22.04 Codename: jammy
> 
> gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04)
> 
> use the installl.sh Unable to compile successfully my opencv-rust project

I've got the same satuation, by using the fix from @RasmusHogslatt , it's gone.
```
apt install libstdc++-12-abd-dev libc++-dev 
```
