### ISSUE TITLE
"No such file or directory" panics building opencv-rust with `cross`

### ISSUE THREAD

**Issue by ostrosco** [twistedfall/opencv-rust#88]
So I'm using cross (https://github.com/rust-embedded/cross) to cross-compile this crate for Raspberry Pi. I've got OpenCV set up in the Docker container, but when I try to build inside the Docker container I get the following error with several "No such file or directory" panics.

```
✗ PKG_CONFIG_ALLOW_CROSS=1 cross build --target=armv7-unknown-linux-gnueabihf --release
   Compiling opencv v0.29.2     
error: failed to run custom build command for `opencv v0.29.2`

Caused by:
  process didn't exit successfully: `/target/release/build/opencv-a197634da940baa5/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-search=native=/usr/local/lib
cargo:rustc-link-lib=opencv_dnn
cargo:rustc-link-lib=opencv_gapi
cargo:rustc-link-lib=opencv_highgui
cargo:rustc-link-lib=opencv_ml
cargo:rustc-link-lib=opencv_objdetect
cargo:rustc-link-lib=opencv_photo
cargo:rustc-link-lib=opencv_stitching
cargo:rustc-link-lib=opencv_video
cargo:rustc-link-lib=opencv_calib3d
cargo:rustc-link-lib=opencv_features2d
cargo:rustc-link-lib=opencv_flann
cargo:rustc-link-lib=opencv_videoio
cargo:rustc-link-lib=opencv_imgcodecs
cargo:rustc-link-lib=opencv_imgproc
cargo:rustc-link-lib=opencv_core
cargo:rerun-if-changed=hdr_parser.py
cargo:rerun-if-changed=gen_rust.py
cargo:rerun-if-env-changed=OPENCV_HEADER_DIR
cargo:rerun-if-env-changed=OPENCV_PACKAGE_NAME
cargo:rerun-if-env-changed=OPENCV_PKGCONFIG_NAME
cargo:rerun-if-env-changed=OPENCV_LINK_LIBS
cargo:rerun-if-env-changed=OPENCV_LINK_PATHS
cargo:rerun-if-env-changed=OPENCV_INCLUDE_PATHS

--- stderr
=== Setting up OpenCV library from pkg_config
=== OpenCV library configuration: Library {
    pkg_name: "opencv4",
    libs: [
        "opencv_dnn",
        "opencv_gapi",
        "opencv_highgui",
        "opencv_ml",
        "opencv_objdetect",
        "opencv_photo",
        "opencv_stitching",
        "opencv_video",
        "opencv_calib3d",
        "opencv_features2d",
        "opencv_flann",
        "opencv_videoio",
        "opencv_imgcodecs",
        "opencv_imgproc",
        "opencv_core",
    ],
    link_paths: [
        "/usr/local/lib",
    ],
    framework_paths: [],
    include_paths: [
        "/usr/local/include/opencv4/opencv",
        "/usr/local/include/opencv4",
    ],
    version: "4.2.0",
    prefix: "/usr/local",
    libdir: "/usr/local/lib",
}
=== Found OpenCV library version: 4.2.0 in headers located at: /cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.29.2/headers/4
=== Using OpenCV headers from: /cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.29.2/headers/4/opencv2
=== Generating code in: /target/armv7-unknown-linux-gnueabihf/release/build/opencv-52f425c938c04ebf/out
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1188:5
...
```

Any thoughts?

**Comment by twistedfall** [comment]
Can you please build with environment variable `RUST_BACKTRACE` set to `full` so that we can see the line that led to that panic?

**Comment by ostrosco** [comment]
Sure thing:
```
stack backtrace:
   0:     0x5587fba6e074 - backtrace::backtrace::libunwind::trace::heb43798aede8bd30
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x5587fba6e074 - backtrace::backtrace::trace_unsynchronized::had2ba7dec4bd2732
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x5587fba6e074 - std::sys_common::backtrace::_print_fmt::hda61f46e822731b2
                               at src/libstd/sys_common/backtrace.rs:84
   3:     0x5587fba6e074 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hfe37fa5de6572965
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x5587fba9011c - core::fmt::write::h74887d18db27282c
                               at src/libcore/fmt/mod.rs:1025
   5:     0x5587fba69b87 - std::io::Write::write_fmt::h6808f3d5eceed5e5
                               at src/libstd/io/mod.rs:1426
   6:     0x5587fba70bee - std::sys_common::backtrace::_print::hcc0fd4b3552039ef
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x5587fba70bee - std::sys_common::backtrace::print::h1c9c5c1c0505592d
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x5587fba70bee - std::panicking::default_hook::{{closure}}::hefb6085c1ab83a59
                               at src/libstd/panicking.rs:193
   9:     0x5587fba708e1 - std::panicking::default_hook::h1b037d2bf0657ab3
                               at src/libstd/panicking.rs:210
  10:     0x5587fba712cb - std::panicking::rust_panic_with_hook::h787d7f532b084b9a
                               at src/libstd/panicking.rs:471
  11:     0x5587fba70e7e - rust_begin_unwind
                               at src/libstd/panicking.rs:375
  12:     0x5587fba8d79e - core::panicking::panic_fmt::h76b979c035808e69
                               at src/libcore/panicking.rs:84
  13:     0x5587fba8d897 - core::result::unwrap_failed::hca6a012bfa3eb903
                               at src/libcore/result.rs:1188
  14:     0x5587fb7eab43 - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut::h6340226ee0e5fe07
  15:     0x5587fb81adfb - rayon::iter::plumbing::bridge_producer_consumer::helper::h6e7f9fdaddb006a3
  16:     0x5587fb8017d3 - std::panicking::try::do_call::h93a9302851838f9c
  17:     0x5587fba7a0ea - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  18:     0x5587fb81835e - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h2437331b61d77488
  19:     0x5587fba50aee - rayon_core::registry::WorkerThread::wait_until_cold::hb51ae2849fa34e3d
  20:     0x5587fba4f37a - rayon_core::registry::ThreadBuilder::run::h4e8bbaf5cdde9546
  21:     0x5587fba518a1 - std::sys_common::backtrace::__rust_begin_short_backtrace::h7ca6b707e4e6872e
  22:     0x5587fba50e30 - std::panicking::try::do_call::h91567d6b897a632e
  23:     0x5587fba7a0ea - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  24:     0x5587fba53f47 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hc6b05a29785c7ea6
  25:     0x5587fba63c7f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h7bfd6e98bcf6c67e
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/liballoc/boxed.rs:1022
  26:     0x5587fba79320 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h9979661149bbc525
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/liballoc/boxed.rs:1022
  27:     0x5587fba79320 - std::sys_common::thread::start_thread::had0bb4166c065276
                               at src/libstd/sys_common/thread.rs:13
  28:     0x5587fba79320 - std::sys::unix::thread::Thread::new::thread_start::hbc75223688f972da
                               at src/libstd/sys/unix/thread.rs:80
  29:     0x7fc53d5316ba - start_thread
  30:     0x7fc53d05141d - clone
  31:                0x0 - <unknown>
```

**Comment by twistedfall** [comment]
Hm, I kind of expected to see some lines of `build.rs` here. Will it be possible for you to replace `unwrap`s with `expect` with different error messages to see which particular line can’t find the file?

**Comment by ostrosco** [comment]
Great suggestion. It turns out that the Docker image I was using didn't include `python3` by default. Would you be open to a PR that changes some of the unwraps in the build script to expects for better debugging of the build process?

**Comment by twistedfall** [comment]
Of course! Thank you!

**Comment by ostrosco** [comment]
I opened a PR to improve the error messaging during builds somewhat. Regardless, this issue has been resolved by installing python3 in my Docker image. Thanks for the help!
